'use client';

import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';

type Definition = { id: string; name: string; metric: string; leftSource: string; leftMetric: string; operator: string; rightSource: string | null; rightMetric: string | null; constantValue: number | null; scale: number };
export function CalculatedMetricForm({ definitions, canManage }: { definitions: Definition[]; canManage: boolean }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [message, setMessage] = useState(''); const [rightMode, setRightMode] = useState<'metric' | 'constant'>('metric');
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); const form = new FormData(event.currentTarget); const useConstant = rightMode === 'constant'; const body = { name: form.get('name'), metric: form.get('metric'), leftSource: form.get('leftSource'), leftMetric: form.get('leftMetric'), operator: form.get('operator'), ...(useConstant ? { constantValue: Number(form.get('constantValue')) } : { rightSource: form.get('rightSource'), rightMetric: form.get('rightMetric') }), scale: Number(form.get('scale')) }; const response = await fetch('/api/calculated-metrics', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); const result = await response.json() as { error?: string; calculated?: { written: number } }; setPending(false); setMessage(result.error || `Metric created; ${result.calculated?.written || 0} calculated points refreshed.`); if (response.ok) { (event.target as HTMLFormElement).reset(); setRightMode('metric'); router.refresh(); } }
  async function recalculate() { setPending(true); const response = await fetch('/api/calculated-metrics', { method: 'PATCH' }); const result = await response.json() as { error?: string; calculated?: { written: number } }; setPending(false); setMessage(result.error || `${result.calculated?.written || 0} calculated points refreshed.`); if (response.ok) router.refresh(); }
  async function remove(id: string) { if (!window.confirm('Delete this formula and its calculated points?')) return; setPending(true); const response = await fetch('/api/calculated-metrics', { method: 'DELETE', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id }) }); const result = await response.json() as { error?: string }; setPending(false); setMessage(result.error || 'Calculated metric deleted.'); if (response.ok) router.refresh(); }
  return <div className="calculated-metric-controls"><form className="connector-form" onSubmit={create}><h3>Create a deterministic formula</h3><div className="settings-grid"><label>Display name<input name="name" required placeholder="Signup conversion" /></label><label>Output metric<input name="metric" required pattern="[a-z][a-z0-9_]{0,63}" placeholder="signup_conversion" /></label><label>Left source<input name="leftSource" required pattern="[a-z][a-z0-9_]{0,63}" placeholder="ga4" /></label><label>Left metric<input name="leftMetric" required pattern="[a-z][a-z0-9_]{0,63}" placeholder="conversions" /></label><label>Operator<select name="operator" defaultValue="divide"><option value="add">Add</option><option value="subtract">Subtract</option><option value="multiply">Multiply</option><option value="divide">Divide</option></select></label><label>Right side<select name="rightMode" value={rightMode} onChange={(event) => setRightMode(event.target.value as 'metric' | 'constant')}><option value="metric">Another metric</option><option value="constant">A constant</option></select></label>{rightMode === 'metric' ? <><label>Right source<input name="rightSource" required pattern="[a-z][a-z0-9_]{0,63}" placeholder="ga4" /></label><label>Right metric<input name="rightMetric" required pattern="[a-z][a-z0-9_]{0,63}" placeholder="signups" /></label></> : <label>Constant<input name="constantValue" type="number" step="any" required defaultValue="1" /></label>}<label>Scale<input name="scale" type="number" step="any" required defaultValue="1" /></label></div><footer><small>Formulas align product, date, and currency. They never execute code or mix currencies.</small><div><button className="app-secondary" type="button" disabled={!canManage || pending} onClick={recalculate}>Recalculate</button><button className="app-primary" disabled={!canManage || pending}>{pending ? 'Working…' : 'Create metric'}</button></div></footer>{message && <p className="form-message" role="status">{message}</p>}</form><section className="app-panel workspace-list"><div className="panel-title"><div><span>FORMULAS</span><h2>{definitions.length} calculated metrics</h2></div></div>{definitions.map((definition) => <article className="report-row" key={definition.id}><div><strong>{definition.name}</strong><small>{definition.metric} = {definition.leftSource}.{definition.leftMetric} {symbol(definition.operator)} {definition.rightSource ? `${definition.rightSource}.${definition.rightMetric}` : definition.constantValue} × {definition.scale}</small></div><span>calculated</span><button className="report-deliver" type="button" disabled={!canManage || pending} onClick={() => remove(definition.id)}>Delete</button></article>)}{!definitions.length && <div className="panel-empty"><p>No calculated metrics yet.</p></div>}</section></div>;
}
function symbol(operator: string) { return ({ add: '+', subtract: '−', multiply: '×', divide: '÷' } as Record<string, string>)[operator] || operator; }
