'use client';

import { FormEvent, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';

export function CloudflareForm({ products }: { products: Array<{ id: string; name: string }> }) {
  const router = useRouter(); const formRef = useRef<HTMLFormElement>(null); const [pending, setPending] = useState(false); const [message, setMessage] = useState(''); const [workers, setWorkers] = useState<Array<{ id: string; name: string }>>([]);
  async function discover() { const form = formRef.current; if (!form) return; const data = new FormData(form); const accountId = String(data.get('accountId') || ''); const apiToken = String(data.get('apiToken') || ''); if (accountId.length < 20 || apiToken.length < 20) { setMessage('Enter the Account ID and API token before discovering Workers.'); return; } setPending(true); setMessage('Discovering Workers with read-only access…'); const response = await fetch('/api/connectors/cloudflare/discover', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ accountId, apiToken }) }); const result = await response.json() as { error?: string; workers?: Array<{ id: string; name: string }> }; setPending(false); setWorkers(result.workers || []); setMessage(result.error || (result.workers?.length ? `${result.workers.length} Workers discovered. Choose one below.` : 'No Workers were found. You can still enter a script name manually.')); }
  async function connect(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setMessage('Validating Cloudflare access…'); const form = new FormData(event.currentTarget); const response = await fetch('/api/connectors/cloudflare', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(Object.fromEntries(form)) }); const result = await response.json() as { error?: string }; setPending(false); setMessage(result.error || 'Cloudflare account and Worker mapping connected.'); if (response.ok) { (event.target as HTMLFormElement).reset(); router.refresh(); } }
  async function sync() { setPending(true); setMessage('Syncing the last 14 days…'); const response = await fetch('/api/sync/cloudflare', { method: 'POST' }); const result = await response.json() as { error?: string; written?: number }; setPending(false); setMessage(result.error || `${result.written || 0} Cloudflare metric points synchronized.`); if (response.ok) router.refresh(); }
  return <form ref={formRef} className="connector-form" onSubmit={connect}><div className="settings-grid"><label>Connection name<input name="displayName" required placeholder="Acme Cloudflare" /></label><label>Account ID<input name="accountId" required minLength={20} placeholder="Cloudflare account ID" /></label><label>API token<input name="apiToken" required type="password" autoComplete="new-password" minLength={20} placeholder="Analytics + Workers Scripts Read token" /></label><label>Product<select name="productId" required disabled={!products.length}>{products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label>Worker script name<input name="workerName" list="cloudflare-worker-options" required placeholder="Discover or enter a Worker name" /><datalist id="cloudflare-worker-options">{workers.map((worker) => <option value={worker.name} key={worker.id} />)}</datalist></label></div><footer><small>Account Analytics Read is required for sync. Add Workers Scripts Read to discover names automatically; manual entry remains available.</small><div><button className="app-secondary" type="button" disabled={pending} onClick={discover}>Discover Workers</button><button className="app-secondary" type="button" disabled={pending} onClick={sync}>Sync connected accounts</button><button className="app-primary" disabled={pending || !products.length}>{pending ? 'Working…' : 'Connect Worker'}</button></div></footer>{message && <p className="form-message" role="status">{message}</p>}</form>;
}
