'use client';

import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';

export function CloudflareR2Form({ products }: { products: Array<{ id: string; name: string }> }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [message, setMessage] = useState('');
  async function connect(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setMessage('Validating R2 Analytics access and bucket name…'); const response = await fetch('/api/connectors/cloudflare/r2', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); const result = await response.json() as { error?: string; mapping?: { bucketName: string } }; setPending(false); setMessage(result.error || `R2 bucket ${result.mapping?.bucketName || ''} validated with 31-day Analytics coverage.`); if (response.ok) { (event.target as HTMLFormElement).reset(); router.refresh(); } }
  async function sync() { setPending(true); setMessage('Syncing the latest 31 days of R2 evidence…'); const response = await fetch('/api/sync/cloudflare-r2', { method: 'POST' }); const result = await response.json() as { error?: string; written?: number }; setPending(false); setMessage(result.error || `${result.written || 0} R2 metric points synchronized with provider-retention disclosure.`); if (response.ok) router.refresh(); }
  return <form className="connector-form" onSubmit={connect}><div className="settings-grid"><label>Connection name<input name="displayName" required placeholder="Acme Cloudflare R2" /></label><label>Account ID<input name="accountId" required minLength={20} placeholder="Cloudflare account ID" /></label><label>API token<input name="apiToken" required type="password" autoComplete="new-password" minLength={20} placeholder="Account Analytics Read token" /></label><label>Product<select name="productId" required disabled={!products.length}>{products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label>R2 analytics bucket name<input name="bucketName" required placeholder="bucket-name or eu_bucket-name" /></label></div><footer><small>Use Account Analytics Read. For jurisdiction-restricted buckets, include the jurisdiction prefix shown by Cloudflare, such as eu_bucket-name. No objects or object names are read.</small><div><button className="app-secondary" type="button" disabled={pending} onClick={sync}>Sync R2</button><button className="app-primary" disabled={pending || !products.length}>{pending ? 'Working…' : 'Connect R2'}</button></div></footer>{message && <p className="form-message" role="status">{message}</p>}</form>;
}
