'use client';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';

export function CloudflareQueuesForm({ products }: { products: Array<{ id: string; name: string }> }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [message, setMessage] = useState('');
  async function connect(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setMessage('Validating Queues Read access and realtime metrics…'); const response = await fetch('/api/connectors/cloudflare/queues', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); const result = await response.json() as { error?: string; mapping?: { queueName: string } }; setPending(false); setMessage(result.error || `Queue ${result.mapping?.queueName || ''} connected with best-effort realtime evidence.`); if (response.ok) { (event.target as HTMLFormElement).reset(); router.refresh(); } }
  async function sync() { setPending(true); setMessage('Capturing current Queue backlog and delivery state…'); const response = await fetch('/api/sync/cloudflare-queues', { method: 'POST' }); const result = await response.json() as { error?: string; written?: number }; setPending(false); setMessage(result.error || `${result.written || 0} Queue metric points synchronized.`); if (response.ok) router.refresh(); }
  return <form className="connector-form" onSubmit={connect}><div className="settings-grid"><label>Connection name<input name="displayName" required placeholder="Acme production queues" /></label><label>Account ID<input name="accountId" required minLength={20} maxLength={32} placeholder="Cloudflare account ID" /></label><label>Queues Read API token<input name="apiToken" required type="password" autoComplete="new-password" minLength={20} placeholder="Scoped API token" /></label><label>Product<select name="productId" required disabled={!products.length}>{products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label>Queue ID<input name="queueId" required maxLength={64} placeholder="Queue resource ID" /></label></div><footer><small>Grant Queues Read only. Dashloom stores approximate backlog totals, oldest-message age, and paused state—not message bodies, producers, consumers, or message identifiers.</small><div><button className="app-secondary" type="button" disabled={pending} onClick={sync}>Sync Queues</button><button className="app-primary" disabled={pending || !products.length}>{pending ? 'Working…' : 'Connect Queue'}</button></div></footer>{message && <p className="form-message" role="status">{message}</p>}</form>;
}
