'use client';

import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';

export function CreemForm({ products }: { products: Array<{ id: string; name: string }> }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [message, setMessage] = useState('');
  async function connect(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); setPending(true); setMessage('Validating Creem server API access…'); const response = await fetch('/api/connectors/creem', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...values, creemProductId: values.creemProductId || null }) }); const result = await response.json() as { error?: string; connector?: { environment: string; transactionCount: number } }; setPending(false); setMessage(result.error || `Creem ${result.connector?.environment || ''} connection validated with ${result.connector?.transactionCount || 0} matching transactions.`); if (response.ok) { (event.target as HTMLFormElement).reset(); router.refresh(); } }
  async function sync() { setPending(true); setMessage('Syncing privacy-minimized Creem revenue evidence…'); const response = await fetch('/api/sync/creem', { method: 'POST' }); const result = await response.json() as { error?: string; written?: number }; setPending(false); setMessage(result.error || `${result.written || 0} Creem metric points synchronized.`); if (response.ok) router.refresh(); }
  return <form className="connector-form" onSubmit={connect}><div className="settings-grid"><label>Connection name<input name="displayName" required placeholder="Acme Creem" /></label><label>Product<select name="productId" required disabled={!products.length}>{products.map((product) => <option value={product.id} key={product.id}>{product.name}</option>)}</select></label><label>Environment<select name="environment" defaultValue="production"><option value="production">Production</option><option value="test">Test mode</option></select></label><label>Creem Product ID (optional)<input name="creemProductId" placeholder="prod_…" /></label><label>API Key<input name="apiKey" type="password" autoComplete="new-password" required minLength={20} placeholder="creem_…" /></label></div><footer><small>Dashloom reads transaction amounts, currency, status, and timestamps only. Customer identity, descriptions, tax country, and metadata are never stored.</small><div><button className="app-secondary" type="button" disabled={pending} onClick={sync}>Sync Creem</button><button className="app-primary" disabled={pending || !products.length}>{pending ? 'Working…' : 'Connect Creem'}</button></div></footer>{message && <p className="form-message" role="status">{message}</p>}</form>;
}
