'use client';

import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';

type Connection = { id: string; displayName: string; status: string };

export function CustomRestForm({ products, connections, canManage }: { products: Array<{ id: string; name: string }>; connections: Connection[]; canManage: boolean }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [message, setMessage] = useState(''); const [authType, setAuthType] = useState('none');
  async function connect(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setMessage('Validating the endpoint and contract without storing response content…'); const response = await fetch('/api/connectors/custom-rest', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); const result = await response.json() as { error?: string; connector?: { endpoint: string; metricCount: number } }; setPending(false); setMessage(result.error || `${result.connector?.endpoint || 'Endpoint'} connected with ${result.connector?.metricCount || 0} valid metrics.`); if (response.ok) { (event.target as HTMLFormElement).reset(); setAuthType('none'); router.refresh(); } }
  async function sync() { setPending(true); setMessage('Pulling bounded normalized metrics…'); const response = await fetch('/api/sync/custom-rest', { method: 'POST' }); const result = await response.json() as { error?: string; written?: number }; setPending(false); setMessage(result.error || `${result.written || 0} Custom REST metric points synchronized.`); if (response.ok) router.refresh(); }
  async function disable(id: string) { if (!window.confirm('Disable this endpoint and permanently remove its stored credential? Historical metric evidence remains.')) return; setPending(true); const response = await fetch(`/api/connectors/accounts/${encodeURIComponent(id)}`, { method: 'DELETE' }); const result = await response.json() as { error?: string }; setPending(false); setMessage(result.error || 'Endpoint disabled, mappings stopped, and stored credential removed.'); if (response.ok) router.refresh(); }
  return <form className="connector-form" onSubmit={connect}><div className="settings-grid"><label>Connection name<input name="displayName" required minLength={2} maxLength={80} placeholder="Acme business metrics" /></label><label>Product<select name="productId" required disabled={!products.length}>{products.map((product) => <option value={product.id} key={product.id}>{product.name}</option>)}</select></label><label>HTTPS JSON endpoint<input name="endpointUrl" type="url" required placeholder="https://api.example.com/dashloom/metrics" /></label><label>Authentication<select name="authType" value={authType} onChange={(event) => setAuthType(event.target.value)}><option value="none">None</option><option value="bearer">Bearer token</option><option value="api_key">Custom API key header</option></select></label>{authType === 'api_key' && <label>Header name<input name="headerName" required pattern="X-[A-Za-z0-9-]{1,60}" placeholder="X-API-Key" /></label>}{authType !== 'none' && <label>Credential<input name="secret" type="password" autoComplete="new-password" required maxLength={2000} placeholder="Encrypted and never displayed again" /></label>}</div><footer><small>GET only. The endpoint must return contract v1 JSON, stay under 1 MiB, and use a public HTTPS host. Query-string credentials and redirects are rejected.</small><div><button className="app-secondary" type="button" disabled={pending || !connections.some((item) => item.status === 'connected')} onClick={sync}>Sync Custom REST</button><button className="app-primary" disabled={pending || !products.length || !canManage}>{pending ? 'Working…' : 'Connect endpoint'}</button></div></footer>{connections.map((connection) => <article className="report-row report-row-action" key={connection.id}><div><strong>{connection.displayName}</strong><small>Custom REST endpoint</small></div><span>custom</span><b data-status={connection.status}>{connection.status}</b><button type="button" className="report-deliver" disabled={!canManage || pending || connection.status === 'disabled'} onClick={() => disable(connection.id)}>{connection.status === 'disabled' ? 'Removed' : 'Disable'}</button></article>)}{message && <p className="form-message" role="status">{message}</p>}</form>;
}
