'use client';

import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';

export function LemonSqueezyForm({ products }: { products: Array<{ id: string; name: string }> }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [message, setMessage] = useState('');
  async function connect(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setMessage('Validating Lemon Squeezy API access and Store ID…'); const response = await fetch('/api/connectors/lemonsqueezy', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); const result = await response.json() as { error?: string; connector?: { currency: string } }; setPending(false); setMessage(result.error || `Lemon Squeezy connected in ${result.connector?.currency?.toUpperCase() || 'the store currency'}.`); if (response.ok) { (event.target as HTMLFormElement).reset(); router.refresh(); } }
  async function sync() { setPending(true); setMessage('Syncing Lemon Squeezy order and subscription evidence…'); const response = await fetch('/api/sync/lemonsqueezy', { method: 'POST' }); const result = await response.json() as { error?: string; written?: number }; setPending(false); setMessage(result.error || `${result.written || 0} Lemon Squeezy metric points synchronized.`); if (response.ok) router.refresh(); }
  return <form className="connector-form" onSubmit={connect}><div className="settings-grid"><label>Connection name<input name="displayName" required placeholder="Acme Lemon Squeezy" /></label><label>Product<select name="productId" required disabled={!products.length}>{products.map((product) => <option value={product.id} key={product.id}>{product.name}</option>)}</select></label><label>Store ID<input name="storeId" inputMode="numeric" required pattern="[0-9]+" placeholder="12345" /></label><label>API Key<input name="apiKey" type="password" autoComplete="new-password" required minLength={20} placeholder="eyJ…" /></label></div><footer><small>Create a Lemon Squeezy API key and enter the numeric Store ID. Dashloom reads the Store, recent Orders, Subscriptions, and referenced Prices; test-mode records and usage-based MRR are excluded.</small><div><button className="app-secondary" type="button" disabled={pending} onClick={sync}>Sync Lemon Squeezy</button><button className="app-primary" disabled={pending || !products.length}>{pending ? 'Working…' : 'Connect Lemon Squeezy'}</button></div></footer>{message && <p className="form-message" role="status">{message}</p>}</form>;
}
