'use client';

import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';

export function PaddleForm({ products }: { products: Array<{ id: string; name: string }> }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [message, setMessage] = useState('');
  async function connect(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); setPending(true); setMessage('Validating Paddle transaction.read and adjustment.read access…'); const response = await fetch('/api/connectors/paddle', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(values) }); const result = await response.json() as { error?: string; connector?: { environment: string; transactionCount: number; adjustmentCount: number } }; setPending(false); setMessage(result.error || `Paddle ${result.connector?.environment || ''} connection validated with ${result.connector?.transactionCount || 0} transactions and ${result.connector?.adjustmentCount || 0} adjustments.`); if (response.ok) { (event.target as HTMLFormElement).reset(); router.refresh(); } }
  async function sync() { setPending(true); setMessage('Syncing privacy-minimized Paddle revenue evidence…'); const response = await fetch('/api/sync/paddle', { method: 'POST' }); const result = await response.json() as { error?: string; written?: number }; setPending(false); setMessage(result.error || `${result.written || 0} Paddle metric points synchronized.`); if (response.ok) router.refresh(); }
  return <form className="connector-form" onSubmit={connect}><div className="settings-grid"><label>Connection name<input name="displayName" required placeholder="Acme Paddle" /></label><label>Product<select name="productId" required disabled={!products.length}>{products.map((product) => <option value={product.id} key={product.id}>{product.name}</option>)}</select></label><label>Environment<select name="environment" defaultValue="production"><option value="production">Production</option><option value="sandbox">Sandbox</option></select></label><label>Server API Key<input name="apiKey" type="password" autoComplete="new-password" required minLength={20} placeholder="pdl_live_apikey_…" /></label></div><footer><small>Grant only transaction.read and adjustment.read. Dashloom stores daily currency totals, refunds, chargebacks, and counts—not customer, address, invoice, item, or transaction identities.</small><div><button className="app-secondary" type="button" disabled={pending} onClick={sync}>Sync Paddle</button><button className="app-primary" disabled={pending || !products.length}>{pending ? 'Working…' : 'Connect Paddle'}</button></div></footer>{message && <p className="form-message" role="status">{message}</p>}</form>;
}
