'use client';

import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';

export function PolarForm({ products }: { products: Array<{ id: string; name: string }> }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [message, setMessage] = useState('');
  async function connect(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); setPending(true); setMessage('Validating Polar orders:read access…'); const response = await fetch('/api/connectors/polar', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...values, polarProductId: values.polarProductId || null }) }); const result = await response.json() as { error?: string; connector?: { environment: string; orderCount: number } }; setPending(false); setMessage(result.error || `Polar ${result.connector?.environment || ''} connection validated with ${result.connector?.orderCount || 0} matching orders.`); if (response.ok) { (event.target as HTMLFormElement).reset(); router.refresh(); } }
  async function sync() { setPending(true); setMessage('Syncing privacy-minimized Polar revenue evidence…'); const response = await fetch('/api/sync/polar', { method: 'POST' }); const result = await response.json() as { error?: string; written?: number }; setPending(false); setMessage(result.error || `${result.written || 0} Polar metric points synchronized.`); if (response.ok) router.refresh(); }
  return <form className="connector-form" onSubmit={connect}><div className="settings-grid"><label>Connection name<input name="displayName" required placeholder="Acme Polar" /></label><label>Product<select name="productId" required disabled={!products.length}>{products.map((product) => <option value={product.id} key={product.id}>{product.name}</option>)}</select></label><label>Environment<select name="environment" defaultValue="production"><option value="production">Production</option><option value="sandbox">Sandbox</option></select></label><label>Polar Product ID (optional)<input name="polarProductId" placeholder="UUID" /></label><label>Organization Access Token<input name="accessToken" type="password" autoComplete="new-password" required minLength={20} placeholder="polar_oat_…" /></label></div><footer><small>Grant only orders:read. Dashloom stores daily amount, refund, transaction count, and currency aggregates—not customers, addresses, descriptions, metadata, invoices, or order IDs.</small><div><button className="app-secondary" type="button" disabled={pending} onClick={sync}>Sync Polar</button><button className="app-primary" disabled={pending || !products.length}>{pending ? 'Working…' : 'Connect Polar'}</button></div></footer>{message && <p className="form-message" role="status">{message}</p>}</form>;
}
