'use client';

import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';

export function SupabaseForm({ products }: { products: Array<{ id: string; name: string }> }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [message, setMessage] = useState('');
  async function connect(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); setPending(true); setMessage('Validating read-only Supabase Management API access…'); const response = await fetch('/api/connectors/supabase', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(values) }); const result = await response.json() as { error?: string; connector?: { projectName: string; status: string; usagePoints: number } }; setPending(false); setMessage(result.error || `${result.connector?.projectName || 'Supabase project'} validated (${result.connector?.status || 'unknown'}) with ${result.connector?.usagePoints || 0} usage periods.`); if (response.ok) { (event.target as HTMLFormElement).reset(); router.refresh(); } }
  async function sync() { setPending(true); setMessage('Syncing aggregated Supabase operations evidence…'); const response = await fetch('/api/sync/supabase', { method: 'POST' }); const result = await response.json() as { error?: string; written?: number }; setPending(false); setMessage(result.error || `${result.written || 0} Supabase metric points synchronized.`); if (response.ok) router.refresh(); }
  return <form className="connector-form" onSubmit={connect}><div className="settings-grid"><label>Connection name<input name="displayName" required placeholder="Acme Supabase production" /></label><label>Product<select name="productId" required disabled={!products.length}>{products.map((product) => <option value={product.id} key={product.id}>{product.name}</option>)}</select></label><label>Project ref<input name="projectRef" required minLength={20} maxLength={20} pattern="[a-z]{20}" placeholder="abcdefghijklmnopqrst" /></label><label>Fine-grained access token<input name="accessToken" type="password" autoComplete="new-password" required minLength={20} placeholder="sbp_…" /></label></div><footer><small>Grant only projects:read and analytics usage read. Dashloom never reads database tables, Auth users, logs, API keys, or project secrets.</small><div><button className="app-secondary" type="button" disabled={pending} onClick={sync}>Sync Supabase</button><button className="app-primary" disabled={pending || !products.length}>{pending ? 'Working…' : 'Connect Supabase'}</button></div></footer>{message && <p className="form-message" role="status">{message}</p>}</form>;
}
