'use client';

import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';

type Schedule = { id: string; source: string; frequencyMinutes: number; enabled: boolean; nextRunAt: string; lastSuccessAt: string | null; retryAttempt: number; lastError: string | null };
const sources = [['cloudflare', 'Cloudflare Workers'], ['cloudflare_r2', 'Cloudflare R2'], ['cloudflare_pages', 'Cloudflare Pages'], ['cloudflare_queues', 'Cloudflare Queues'], ['google', 'Google'], ['stripe', 'Stripe revenue'], ['lemonsqueezy', 'Lemon Squeezy revenue'], ['creem', 'Creem revenue'], ['polar', 'Polar revenue'], ['supabase', 'Supabase operations'], ['github', 'GitHub'], ['vercel', 'Vercel'], ['d1', 'D1 business metrics'], ['custom', 'Custom REST metrics']] as const;

export function SyncScheduleForm({ schedules, minimumMinutes, canManage }: { schedules: Schedule[]; minimumMinutes: number; canManage: boolean }) {
  const router = useRouter(); const [message, setMessage] = useState(''); const [pending, setPending] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setPending(true); const response = await fetch('/api/sync-schedules', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ source: form.get('source'), frequencyMinutes: Number(form.get('frequencyMinutes')), enabled: true }) }); const result = await response.json() as { error?: string }; setPending(false); setMessage(result.error || 'Automatic synchronization schedule saved.'); if (response.ok) router.refresh(); }
  return <section className="connector-form"><h3>Automatic synchronization</h3><form className="schedule-inline" onSubmit={submit}><label>Source<select name="source" defaultValue="cloudflare">{sources.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Frequency<select name="frequencyMinutes" defaultValue={String(Math.max(minimumMinutes, 60))}><option value="15" disabled={minimumMinutes > 15}>Every 15 minutes</option><option value="60" disabled={minimumMinutes > 60}>Hourly</option><option value="360" disabled={minimumMinutes > 360}>Every 6 hours</option><option value="1440">Daily</option><option value="10080">Weekly</option></select></label><button className="app-primary" disabled={!canManage || pending}>{pending ? 'Saving…' : 'Save schedule'}</button></form><small>{message || `Your plan allows synchronization every ${minimumMinutes} minutes or slower. Failed runs use exponential retry backoff.`}</small>{schedules.map((schedule) => <article className="report-row" key={schedule.id}><div><strong>{schedule.source}</strong><small>{schedule.lastError || (schedule.lastSuccessAt ? `Last success ${new Date(schedule.lastSuccessAt).toLocaleString()}` : 'Waiting for first run')}</small></div><span>{schedule.frequencyMinutes} min</span><b data-status={schedule.lastError ? 'attention' : 'connected'}>{schedule.enabled ? (schedule.retryAttempt ? `retry ${schedule.retryAttempt}` : 'active') : 'off'}</b></article>)}</section>;
}
