'use client';

import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';

type Schedule = { id: string; source: string; frequencyMinutes: number; enabled: boolean; nextRunAt: string; lastSuccessAt: string | null; retryAttempt: number; lastError: string | null };
const sources = [['google', 'Google'], ['bing', 'Bing Webmaster'], ['stripe', 'Stripe revenue'], ['lemonsqueezy', 'Lemon Squeezy revenue'], ['creem', 'Creem revenue'], ['polar', 'Polar revenue'], ['paddle', 'Paddle Billing revenue'], ['d1', 'D1 business metrics'], ['custom', 'Custom REST metrics']] as const;

export function SyncScheduleForm({ schedules, minimumMinutes, canManage, zh = false }: { schedules: Schedule[]; minimumMinutes: number; canManage: boolean; zh?: boolean }) {
  const router = useRouter(); const [message, setMessage] = useState(''); const [pending, setPending] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setPending(true); const response = await fetch('/api/sync-schedules', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ source: form.get('source'), frequencyMinutes: Number(form.get('frequencyMinutes')), enabled: true }) }); const result = await response.json() as { error?: string }; setPending(false); setMessage(result.error || (zh ? '自动同步计划已保存。' : 'Automatic synchronization schedule saved.')); if (response.ok) router.refresh(); }
  return <section className="connector-form"><h3>{zh ? '自动同步' : 'Automatic synchronization'}</h3><form className="schedule-inline" onSubmit={submit}><label>{zh ? '数据源' : 'Source'}<select name="source" defaultValue="google">{sources.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>{zh ? '频率' : 'Frequency'}<select name="frequencyMinutes" defaultValue={String(Math.max(minimumMinutes, 60))}><option value="15" disabled={minimumMinutes > 15}>{zh ? '每 15 分钟' : 'Every 15 minutes'}</option><option value="60" disabled={minimumMinutes > 60}>{zh ? '每小时' : 'Hourly'}</option><option value="360" disabled={minimumMinutes > 360}>{zh ? '每 6 小时' : 'Every 6 hours'}</option><option value="1440">{zh ? '每天' : 'Daily'}</option><option value="10080">{zh ? '每周' : 'Weekly'}</option></select></label><button className="app-primary" disabled={!canManage || pending}>{pending ? (zh ? '保存中…' : 'Saving…') : (zh ? '保存计划' : 'Save schedule')}</button></form><small>{message || (zh ? `当前部署允许每 ${minimumMinutes} 分钟或更慢的同步；失败任务会按指数退避重试。` : `This deployment allows synchronization every ${minimumMinutes} minutes or slower. Failed runs use exponential retry backoff.`)}</small>{schedules.map((schedule) => <article className="report-row" key={schedule.id}><div><strong>{schedule.source}</strong><small>{schedule.lastError || (schedule.lastSuccessAt ? `${zh ? '上次成功' : 'Last success'} ${new Date(schedule.lastSuccessAt).toLocaleString(zh ? 'zh-CN' : 'en-US')}` : (zh ? '等待首次运行' : 'Waiting for first run'))}</small></div><span>{schedule.frequencyMinutes} {zh ? '分钟' : 'min'}</span><b data-status={schedule.lastError ? 'attention' : 'connected'}>{schedule.enabled ? (schedule.retryAttempt ? `${zh ? '重试' : 'retry'} ${schedule.retryAttempt}` : (zh ? '启用' : 'active')) : (zh ? '关闭' : 'off')}</b></article>)}</section>;
}
