import { and, eq, inArray, sql } from 'drizzle-orm';
import { NextResponse } from 'next/server';
import { z } from 'zod';
import { getDb } from '@/db';
import { competitorMetricPoints, competitors } from '@/db/schema';
import { createAuth } from '@/lib/auth';
import { getPrimaryWorkspace } from '@/lib/workspaces';

const row = z.object({ competitorId: z.string().uuid(), source: z.string().trim().min(1).max(40), metric: z.string().trim().regex(/^[a-z][a-z0-9_]{1,79}$/), metricDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), value: z.number().finite(), dimensions: z.record(z.string(), z.union([z.string(), z.number(), z.boolean()])).optional().default({}), provenance: z.object({ url: z.string().url().optional(), observedAt: z.string().datetime().optional(), note: z.string().max(500).optional() }).optional().default({}) });
const input = z.object({ rows: z.array(row).min(1).max(1000) });
export async function POST(request: Request) { const session = await createAuth().api.getSession({ headers: request.headers }); if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const workspace = await getPrimaryWorkspace(session.user.id); if (!workspace) return NextResponse.json({ error: 'Workspace not found' }, { status: 404 }); if (!['owner', 'admin', 'member'].includes(workspace.role)) return NextResponse.json({ error: 'Member access required' }, { status: 403 }); const parsed = input.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message || 'Invalid competitor metrics' }, { status: 400 }); const ids = [...new Set(parsed.data.rows.map((item) => item.competitorId))]; const owned = await getDb().select({ id: competitors.id }).from(competitors).where(and(eq(competitors.workspaceId, workspace.id), inArray(competitors.id, ids))); if (owned.length !== ids.length) return NextResponse.json({ error: 'A competitor does not belong to this workspace' }, { status: 403 }); let written = 0; for (let index = 0; index < parsed.data.rows.length; index += 8) { const chunk = parsed.data.rows.slice(index, index + 8).map((item) => ({ workspaceId: workspace.id, competitorId: item.competitorId, source: item.source, metric: item.metric, metricDate: item.metricDate, value: item.value, dimensionsJson: JSON.stringify(item.dimensions), provenanceJson: JSON.stringify(item.provenance), collectedAt: new Date().toISOString() })); await getDb().insert(competitorMetricPoints).values(chunk).onConflictDoUpdate({ target: [competitorMetricPoints.competitorId, competitorMetricPoints.source, competitorMetricPoints.metric, competitorMetricPoints.metricDate, competitorMetricPoints.dimensionsJson], set: { value: sql`excluded.value`, provenanceJson: sql`excluded.provenance_json`, collectedAt: sql`excluded.collected_at` } }); written += chunk.length; } return NextResponse.json({ written }); }
