import { and, eq } from 'drizzle-orm';
import { NextResponse } from 'next/server';
import { z } from 'zod';
import { getDb } from '@/db';
import { connectorAccounts, productConnectorMappings, products } from '@/db/schema';
import { recordAuditEvent } from '@/lib/audit';
import { createAuth } from '@/lib/auth';
import { encryptSecret } from '@/lib/crypto';
import { validateStripeCredentials } from '@/lib/stripe-connector';
import { getPrimaryWorkspace } from '@/lib/workspaces';

const input = z.object({ displayName: z.string().trim().min(2).max(80), apiKey: z.string().trim().min(20).max(300), productId: z.string().uuid() });
export async function POST(request: Request) {
  const session = await createAuth().api.getSession({ headers: request.headers }); if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const workspace = await getPrimaryWorkspace(session.user.id); if (!workspace) return NextResponse.json({ error: 'Workspace not found' }, { status: 404 }); if (!['owner', 'admin'].includes(workspace.role)) return NextResponse.json({ error: 'Owner or admin access required' }, { status: 403 }); const parsed = input.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message || 'Invalid Stripe connection' }, { status: 400 }); const [product] = await getDb().select({ id: products.id }).from(products).where(and(eq(products.id, parsed.data.productId), eq(products.workspaceId, workspace.id))).limit(1); if (!product) return NextResponse.json({ error: 'Product not found in this workspace' }, { status: 404 });
  let account: Awaited<ReturnType<typeof validateStripeCredentials>>; try { account = await validateStripeCredentials(parsed.data.apiKey); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : 'Stripe validation failed' }, { status: 422 }); }
  const db = getDb(); const [existing] = await db.select().from(connectorAccounts).where(and(eq(connectorAccounts.workspaceId, workspace.id), eq(connectorAccounts.provider, 'stripe'), eq(connectorAccounts.externalAccountId, account.accountId))).limit(1); const connectorId = existing?.id || crypto.randomUUID(); const encryptedCredentials = await encryptSecret(JSON.stringify({ apiKey: parsed.data.apiKey, defaultCurrency: account.defaultCurrency }), `connector:${workspace.id}:${connectorId}`);
  if (existing) await db.update(connectorAccounts).set({ displayName: parsed.data.displayName, encryptedCredentials, status: 'connected', lastCheckedAt: new Date().toISOString(), updatedAt: new Date().toISOString() }).where(and(eq(connectorAccounts.id, connectorId), eq(connectorAccounts.workspaceId, workspace.id))); else await db.insert(connectorAccounts).values({ id: connectorId, workspaceId: workspace.id, provider: 'stripe', externalAccountId: account.accountId, displayName: parsed.data.displayName, encryptedCredentials, status: 'connected', lastCheckedAt: new Date().toISOString() });
  await db.delete(productConnectorMappings).where(and(eq(productConnectorMappings.workspaceId, workspace.id), eq(productConnectorMappings.connectorAccountId, connectorId), eq(productConnectorMappings.source, 'stripe'))); await db.insert(productConnectorMappings).values({ id: crypto.randomUUID(), workspaceId: workspace.id, productId: product.id, connectorAccountId: connectorId, source: 'stripe', resourceId: account.accountId, resourceLabel: `${account.displayName} · ${account.defaultCurrency.toUpperCase()}`, configurationJson: JSON.stringify({ currency: account.defaultCurrency }), enabled: true }); await recordAuditEvent({ workspaceId: workspace.id, actorUserId: session.user.id, action: 'connector.stripe_connected', targetType: 'connector', targetId: connectorId, metadata: { productId: product.id, currency: account.defaultCurrency } }); return NextResponse.json({ connector: { id: connectorId, displayName: parsed.data.displayName, accountId: account.accountId, currency: account.defaultCurrency, status: 'connected' } }, { status: 201 });
}
