import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = { title: 'Community documentation — Dashloom', description: 'Install and operate the self-hosted Dashloom Community edition.', alternates: { canonical: '/docs' } };

export default function DocsPage() {
  return <main className="content-page"><nav className="site-nav"><Link className="brand" href="/"><span className="brand-mark" aria-hidden="true"><i /><i /><i /></span><span>Dashloom</span></Link><div className="nav-actions"><Link className="text-link" href="/">Home</Link><a className="button button-small" href="https://github.com/dashloom-dev/dashloom">GitHub ↗</a></div></nav><article className="prose-shell"><div className="eyebrow"><span />Community documentation</div><h1>Build and operate your own Dashloom.</h1><p className="lead">This public repository is the standalone self-hosted edition. It uses your infrastructure, your D1 database, and your OpenAI-compatible provider.</p>
    <h2>Local development</h2><pre><code>npm install{`\n`}npm run db:migrate:local{`\n`}npm run dev</code></pre>
    <h2>Core guides</h2><p><a href="https://github.com/dashloom-dev/dashloom/blob/main/docs/architecture.md">Architecture</a> · <a href="https://github.com/dashloom-dev/dashloom/blob/main/docs/cloudflare-setup.md">Cloudflare</a> · <a href="https://github.com/dashloom-dev/dashloom/blob/main/docs/google-cloud-setup.md">Google</a> · <a href="https://github.com/dashloom-dev/dashloom/blob/main/docs/bing-webmaster-setup.md">Bing Webmaster</a> · <a href="https://github.com/dashloom-dev/dashloom/blob/main/docs/stripe-revenue-setup.md">Stripe revenue</a> · <a href="https://github.com/dashloom-dev/dashloom/blob/main/docs/custom-rest-setup.md">Custom REST</a> · <a href="https://github.com/dashloom-dev/dashloom/blob/main/docs/connector-sdk.md">Connector SDK</a> · <a href="https://github.com/dashloom-dev/dashloom/blob/main/docs/agent-skill-sdk.md">Agent Skills</a> · <a href="https://github.com/dashloom-dev/dashloom/blob/main/docs/automated-reports.md">Reports</a></p>
    <h2>Trust boundary</h2><p>Models receive bounded deterministic evidence. Provider content cannot change system policy, credentials remain server-side, and material findings retain citations.</p>
    <div className="notice"><strong>Production activation</strong><p>Use independent secrets, bind the intended D1 database, apply migrations remotely, confirm no pending migration, verify affected tables, and test authentication, connectors, BYOK analysis, schedules, export, and recovery.</p></div>
  </article></main>;
}
