import Link from 'next/link';
import { ArrowDownRight, ArrowUpRight, BarChart3, Database, SlidersHorizontal } from 'lucide-react';
import { requireServerSession } from '@/lib/session';
import { getPrimaryWorkspace } from '@/lib/workspaces';
import { getDeploymentLocale } from '@/lib/deployment-locale';
import { combinedMetricSeries, formatMetric, loadDashboardData, metricDelta, metricLabel, seriesFor } from '@/lib/dashboard-data';
import { DataChart } from '../data-chart';

export default async function ChartsPage({ searchParams }: { searchParams: Promise<{ range?: string; product?: string; metric?: string }> }) {
  const { user } = await requireServerSession(); const workspace = await getPrimaryWorkspace(user.id); const query = await searchParams; if (!workspace) return null;
  const zh = getDeploymentLocale() === 'zh'; const range = [7, 28, 90].includes(Number(query.range)) ? Number(query.range) : 28;
  const { products, points } = await loadDashboardData(workspace.id, 180); const productId = products.some((product) => product.id === query.product) ? query.product! : '';
  const available = seriesFor(points, range, productId || null); const metrics = [...new Set(available.map((item) => item.metric))]; const metric = metrics.includes(query.metric || '') ? query.metric! : metrics[0] || '';
  const selectedSeries = available.filter((item) => item.metric === metric); const selectedProduct = products.find((item) => item.id === productId);
  const trend = combinedMetricSeries(points, metric, range, productId || null);
  const scopedMetricSeries = productId ? selectedSeries : products.flatMap((product) => seriesFor(points, range, product.id).filter((item) => item.metric === metric));
  const currentValue = scopedMetricSeries.reduce((sum, item) => sum + item.current, 0); const previousValue = scopedMetricSeries.reduce((sum, item) => sum + item.previous, 0);
  const periodDelta = previousValue ? ((currentValue - previousValue) / Math.abs(previousValue)) * 100 : null;
  const comparisonLines = productId ? selectedSeries.slice(0, 4).map((item, index) => ({ label: item.source, color: ['#59dbae', '#68a8ff', '#a983ff', '#f2b84b'][index], points: item.values })) : products.filter((item) => item.status !== 'archived').map((product, index) => ({ label: product.name, color: ['#59dbae', '#68a8ff', '#a983ff', '#f2b84b', '#ff8177'][index % 5], points: combinedMetricSeries(points, metric, range, product.id) })).filter((line) => line.points.length).slice(0, 6);
  const detailHref = selectedProduct ? `/dashboard/data/${selectedProduct.id}?range=${range}` : `/dashboard/data?range=${range}`;
  return <div className="app-page charts-page">
    <header className="app-page-head"><div><span>{zh ? '趋势对比' : 'TREND COMPARISON'}</span><h1>{zh ? '图表' : 'Charts'}</h1><p>{zh ? '选择产品、指标和时间范围，查看每天的数值，并与上一周期对比。' : 'Choose a product, metric, and date range to see daily values and compare them with the previous period.'}</p></div><Link className="app-secondary" href={detailHref}>{zh ? '查看数据明细' : 'View data rows'}</Link></header>
    <form className="chart-filter-panel" method="get"><label><span><Database size={15} />{zh ? '产品范围' : 'Product scope'}</span><select name="product" defaultValue={productId}><option value="">{zh ? '全部产品' : 'All products'}</option>{products.filter((product) => product.status !== 'archived').map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label><span><BarChart3 size={15} />{zh ? '指标' : 'Metric'}</span><select name="metric" defaultValue={metric}>{metrics.map((item) => <option key={item} value={item}>{metricLabel(item)}</option>)}</select></label><label><span><SlidersHorizontal size={15} />{zh ? '时间窗口' : 'Time range'}</span><select name="range" defaultValue={String(range)}><option value="7">7 {zh ? '天' : 'days'}</option><option value="28">28 {zh ? '天' : 'days'}</option><option value="90">90 {zh ? '天' : 'days'}</option></select></label><button className="app-primary">{zh ? '应用筛选' : 'Apply filters'}</button></form>
    {metric ? <>
      <section className="chart-kpi-row"><article><span>{zh ? '本周期合计' : 'Current total'}</span><strong>{formatMetric(currentValue, metric)}</strong><small>{selectedProduct?.name || (zh ? '全部产品' : 'All products')} · {range} {zh ? '天' : 'days'}</small></article><article><span>{zh ? '比上一周期' : 'Change from previous'}</span><strong data-tone={(periodDelta || 0) >= 0 ? 'positive' : 'negative'}>{periodDelta === null ? '—' : `${periodDelta >= 0 ? '+' : ''}${periodDelta.toFixed(1)}%`}</strong><small>{zh ? '对比相同天数' : 'same number of days'}</small></article><article><span>{zh ? '图中曲线' : 'Lines shown'}</span><strong>{comparisonLines.length}</strong><small>{productId ? (zh ? '按数据源对比' : 'one line per source') : (zh ? '按产品对比' : 'one line per product')}</small></article><article><span>{zh ? '最新数据日期' : 'Latest data date'}</span><strong>{available.map((item) => item.latestDate).sort().at(-1) || '—'}</strong><small>{zh ? '不是同步时间' : 'date in the source data'}</small></article></section>
      <section className="app-panel chart-workspace"><header><div><span>{selectedProduct ? (zh ? '产品趋势' : 'PRODUCT TREND') : (zh ? '产品组合对比' : 'PORTFOLIO COMPARISON')}</span><h2>{metricLabel(metric)}</h2><p>{zh ? `最近 ${range} 天 · ${selectedProduct?.name || '全部产品'}` : `Last ${range} days · ${selectedProduct?.name || 'all products'}`}</p></div><div className="chart-legend">{comparisonLines.map((line) => <span key={line.label} style={{ '--legend-color': line.color } as React.CSSProperties}>{line.label}</span>)}</div></header><DataChart lines={comparisonLines.length ? comparisonLines : [{ label: metricLabel(metric), color: '#59dbae', points: trend }]} height={360} label={`${metricLabel(metric)} trend chart`} /></section>
      <section className="chart-breakdown-grid"><article className="app-panel"><div className="panel-title"><div><span>{zh ? '来源拆分' : 'SOURCE BREAKDOWN'}</span><h2>{zh ? '当前指标的采集来源' : 'Where this metric comes from'}</h2></div></div><div className="chart-source-list">{selectedSeries.map((item) => { const delta = metricDelta(item); return <div key={`${item.metric}-${item.source}`}><span><strong>{item.source.replaceAll('_', ' ')}</strong><small>{item.latestDate || (zh ? '暂无数据' : 'No evidence')}</small></span><b>{formatMetric(item.current, item.metric)}</b><em data-tone={delta === null ? 'neutral' : delta >= 0 ? 'positive' : 'negative'}>{delta === null ? '—' : <>{delta >= 0 ? <ArrowUpRight size={13} /> : <ArrowDownRight size={13} />}{Math.abs(delta).toFixed(1)}%</>}</em></div>; })}</div></article><article className="app-panel chart-insight-note"><div className="panel-title"><div><span>{zh ? '阅读提示' : 'READING THE CHART'}</span><h2>{zh ? '保留证据边界' : 'Keep evidence boundaries visible'}</h2></div></div><p>{zh ? '图表按标准化指标聚合，但不会把不同币种相加，也不会把相关性包装成因果关系。切换到单个产品可查看数据源和指标明细。' : 'Charts aggregate normalized metrics, but never add unlike currencies or present correlation as causation. Select one product to inspect its source-level evidence.'}</p><Link href={detailHref}>{zh ? '打开明细 →' : 'Open detail →'}</Link></article></section>
    </> : <section className="data-empty app-panel"><Database size={28} /><h2>{zh ? '还没有可绘制的数据' : 'No chartable data yet'}</h2><p>{zh ? '连接数据源并完成首次同步后，指标会自动出现在筛选器中。' : 'Connect a source and complete the first sync. Metrics will then appear in this selector automatically.'}</p><Link className="app-primary" href="/dashboard/sources">{zh ? '连接数据源' : 'Connect data source'}</Link></section>}
  </div>;
}
