import { and, eq } from 'drizzle-orm';
import { NextResponse } from 'next/server';
import { z } from 'zod';
import { getDb } from '@/db';
import { ingestionApiKeys, products } from '@/db/schema';
import { recordAuditEvent } from '@/lib/audit';
import { createAuth } from '@/lib/auth';
import { hashToken, randomToken } from '@/lib/tokens';
import { getPrimaryWorkspace } from '@/lib/workspaces';

const input = z.object({ name: z.string().trim().min(2).max(80), productId: z.string().uuid().nullable().optional().default(null) });
async function context(request: Request) { const session = await createAuth().api.getSession({ headers: request.headers }); if (!session) return null; const workspace = await getPrimaryWorkspace(session.user.id); return workspace ? { session, workspace } : null; }
export async function GET(request: Request) { const value = await context(request); if (!value) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); if (!['owner', 'admin'].includes(value.workspace.role)) return NextResponse.json({ error: 'Owner or admin access required' }, { status: 403 }); const keys = await getDb().select({ id: ingestionApiKeys.id, productId: ingestionApiKeys.productId, name: ingestionApiKeys.name, tokenPrefix: ingestionApiKeys.tokenPrefix, lastUsedAt: ingestionApiKeys.lastUsedAt, revokedAt: ingestionApiKeys.revokedAt, createdAt: ingestionApiKeys.createdAt }).from(ingestionApiKeys).where(eq(ingestionApiKeys.workspaceId, value.workspace.id)).orderBy(ingestionApiKeys.createdAt); return NextResponse.json({ keys }); }
export async function POST(request: Request) { const value = await context(request); if (!value) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); if (!['owner', 'admin'].includes(value.workspace.role)) return NextResponse.json({ error: 'Owner or admin access required' }, { status: 403 }); const parsed = input.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message || 'Invalid key name' }, { status: 400 }); if (parsed.data.productId) { const [product] = await getDb().select({ id: products.id }).from(products).where(and(eq(products.id, parsed.data.productId), eq(products.workspaceId, value.workspace.id))).limit(1); if (!product) return NextResponse.json({ error: 'Product not found in this workspace.' }, { status: 404 }); } const token = `dlm_live_${randomToken()}`; const id = crypto.randomUUID(); await getDb().insert(ingestionApiKeys).values({ id, workspaceId: value.workspace.id, productId: parsed.data.productId, name: parsed.data.name, tokenPrefix: token.slice(0, 17), tokenHash: await hashToken(token), createdByUserId: value.session.user.id }); await recordAuditEvent({ workspaceId: value.workspace.id, actorUserId: value.session.user.id, action: 'ingestion_key.created', targetType: 'ingestion_key', targetId: id, metadata: { scope: parsed.data.productId ? 'product' : 'workspace', productId: parsed.data.productId } }); return NextResponse.json({ key: { id, productId: parsed.data.productId, name: parsed.data.name, token, tokenPrefix: token.slice(0, 17) } }, { status: 201 }); }
export async function DELETE(request: Request) { const value = await context(request); if (!value) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); if (!['owner', 'admin'].includes(value.workspace.role)) return NextResponse.json({ error: 'Owner or admin access required' }, { status: 403 }); const id = new URL(request.url).searchParams.get('id'); if (!id) return NextResponse.json({ error: 'Key id is required' }, { status: 400 }); const revokedAt = new Date().toISOString(); const result = await getDb().update(ingestionApiKeys).set({ revokedAt }).where(and(eq(ingestionApiKeys.id, id), eq(ingestionApiKeys.workspaceId, value.workspace.id))); if (!result.meta.changes) return NextResponse.json({ error: 'Key not found' }, { status: 404 }); await recordAuditEvent({ workspaceId: value.workspace.id, actorUserId: value.session.user.id, action: 'ingestion_key.revoked', targetType: 'ingestion_key', targetId: id }); return NextResponse.json({ revoked: true }); }
