import { and, eq } from 'drizzle-orm';
import { NextResponse } from 'next/server';
import { z } from 'zod';
import { getDb } from '@/db';
import { syncSchedules } from '@/db/schema';
import { recordAuditEvent } from '@/lib/audit';
import { createAuth } from '@/lib/auth';
import { getWorkspaceEntitlements } from '@/lib/entitlements';
import { nextSyncTime } from '@/lib/sync-time';
import { getPrimaryWorkspace } from '@/lib/workspaces';

const syncSource = z.enum(['cloudflare', 'cloudflare_r2', 'cloudflare_pages', 'cloudflare_queues', 'google', 'd1', 'stripe', 'lemonsqueezy', 'creem', 'polar', 'paddle', 'supabase', 'github', 'vercel', 'custom']);
const input = z.object({ source: syncSource, frequencyMinutes: z.number().int().min(15).max(10080), enabled: z.boolean().default(true) });
async function context(request: Request) { const session = await createAuth().api.getSession({ headers: request.headers }); if (!session) return null; const workspace = await getPrimaryWorkspace(session.user.id); return workspace ? { session, workspace } : null; }
export async function GET(request: Request) { const value = await context(request); if (!value) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); return NextResponse.json({ schedules: await getDb().select().from(syncSchedules).where(eq(syncSchedules.workspaceId, value.workspace.id)).orderBy(syncSchedules.source) }); }
export async function POST(request: Request) { const value = await context(request); if (!value) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); if (!['owner', 'admin'].includes(value.workspace.role)) return NextResponse.json({ error: 'Owner or admin access required' }, { status: 403 }); const parsed = input.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message || 'Invalid sync schedule' }, { status: 400 }); const entitlements = await getWorkspaceEntitlements(value.workspace.id); if (parsed.data.frequencyMinutes < entitlements.minimumSyncMinutes) return NextResponse.json({ error: `The ${entitlements.plan} plan supports synchronization every ${entitlements.minimumSyncMinutes} minutes or slower.` }, { status: 403 }); const id = crypto.randomUUID(); const nextRunAt = nextSyncTime(parsed.data.frequencyMinutes); await getDb().insert(syncSchedules).values({ id, workspaceId: value.workspace.id, ...parsed.data, nextRunAt }).onConflictDoUpdate({ target: [syncSchedules.workspaceId, syncSchedules.source], set: { frequencyMinutes: parsed.data.frequencyMinutes, enabled: parsed.data.enabled, nextRunAt, retryAttempt: 0, lastError: null, updatedAt: new Date().toISOString() } }); await recordAuditEvent({ workspaceId: value.workspace.id, actorUserId: value.session.user.id, action: 'sync_schedule.upserted', targetType: 'sync_schedule', targetId: parsed.data.source, metadata: { frequencyMinutes: parsed.data.frequencyMinutes, enabled: parsed.data.enabled } }); return NextResponse.json({ schedule: { source: parsed.data.source, frequencyMinutes: parsed.data.frequencyMinutes, enabled: parsed.data.enabled, nextRunAt } }, { status: 201 }); }
export async function DELETE(request: Request) { const value = await context(request); if (!value) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); if (!['owner', 'admin'].includes(value.workspace.role)) return NextResponse.json({ error: 'Owner or admin access required' }, { status: 403 }); const parsed = syncSource.safeParse(new URL(request.url).searchParams.get('source')); if (!parsed.success) return NextResponse.json({ error: 'Valid source is required' }, { status: 400 }); await getDb().update(syncSchedules).set({ enabled: false, updatedAt: new Date().toISOString() }).where(and(eq(syncSchedules.workspaceId, value.workspace.id), eq(syncSchedules.source, parsed.data))); return NextResponse.json({ disabled: true }); }
