'use client';

import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';

type View = { id: string; preset: string; name: string; productId: string | null; configurationJson: string; isDefault: boolean; origin: 'manual' | 'agent' };
type Product = { id: string; name: string };
export function DashboardViewControls({ views, products }: { views: View[]; products: Product[] }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [message, setMessage] = useState('');
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); const form = new FormData(event.currentTarget); const metrics = String(form.get('metrics') || '').split(',').map((value) => value.trim().toLowerCase()).filter(Boolean); const response = await fetch('/api/dashboard-views', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: form.get('name'), preset: form.get('preset'), productId: form.get('productId') || null, isDefault: form.get('isDefault') === 'on', configuration: { title: form.get('title') || undefined, copy: form.get('copy') || undefined, metrics } }) }); const result = await response.json() as { error?: string }; setPending(false); setMessage(result.error || 'Dashboard view created.'); if (response.ok) { (event.target as HTMLFormElement).reset(); router.refresh(); } }
  async function remove(id: string) { setPending(true); const response = await fetch('/api/dashboard-views', { method: 'DELETE', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id }) }); const result = await response.json() as { error?: string }; setPending(false); setMessage(result.error || 'Dashboard view deleted.'); if (response.ok) router.refresh(); }
  return <div className="dashboard-view-controls">
    <form className="connector-form" onSubmit={create}><h2>Create a reusable dashboard view</h2><div className="settings-grid"><label>View name<input name="name" required placeholder="Weekly founder view" /></label><label>Base template<select name="preset" defaultValue="indie_hacker"><option value="indie_hacker">Indie Hacker</option><option value="saas_revenue">SaaS Revenue</option><option value="seo_growth">SEO Growth</option><option value="cloudflare_operations">Cloudflare Operations</option><option value="agency_client">Agency Client</option></select></label><label>Product scope<select name="productId" defaultValue=""><option value="">All products</option>{products.map((product) => <option value={product.id} key={product.id}>{product.name}</option>)}</select></label><label>Display title<input name="title" placeholder="Founder weekly pulse" /></label><label>Metrics<input name="metrics" required placeholder="revenue, active_users, clicks" /></label><label>Supporting copy<input name="copy" maxLength={300} placeholder="The signals this view should emphasize" /></label><label className="checkbox-label"><input name="isDefault" type="checkbox" /> Use as default for this template</label></div><footer><small>Use normalized metric names separated by commas. A view can include up to eight metrics and remains isolated to this workspace.</small><button className="app-primary" disabled={pending}>{pending ? 'Saving…' : 'Create view'}</button></footer>{message && <p className="form-message" role="status">{message}</p>}</form>
    <section className="app-panel workspace-list"><div className="panel-title"><div><span>SAVED VIEWS</span><h2>{views.length} reusable dashboard views</h2></div></div>{views.map((view) => <article className="report-row report-row-action" key={view.id}><div><strong>{view.name}</strong><small>{view.origin === 'agent' ? 'Agent-generated' : 'Manual'} · {view.preset.replaceAll('_', ' ')} · {view.productId ? 'one product' : 'all products'}{view.isDefault ? ' · default' : ''}</small></div><Link className="report-deliver" href={`/dashboard/views/${view.preset}?view=${view.id}`}>Open</Link><button className="report-deliver" disabled={pending} onClick={() => remove(view.id)}>Delete</button></article>)}{!views.length && <div className="panel-empty"><p>No saved views yet. The five built-in templates remain available in navigation.</p></div>}</section>
  </div>;
}
