import { desc, eq } from 'drizzle-orm';
import { getDb } from '@/db';
import { agentActions, agentGrowthMissions, products } from '@/db/schema';
import { requireServerSession } from '@/lib/session';
import { getPrimaryWorkspace } from '@/lib/workspaces';
import { MissionCancel, MissionRefresh } from './mission-controls';

function formatValue(value: number | null, currency: string | null) {
  if (value === null) return 'Waiting';
  return `${value.toLocaleString(undefined, { maximumFractionDigits: 2 })}${currency ? ` ${currency.toUpperCase()}` : ''}`;
}

export default async function GrowthMissionsPage() {
  const { user } = await requireServerSession(); const workspace = await getPrimaryWorkspace(user.id); if (!workspace) return null;
  const missions = await getDb().select({ mission: agentGrowthMissions, productName: products.name, actionTitle: agentActions.title }).from(agentGrowthMissions).leftJoin(products, eq(agentGrowthMissions.productId, products.id)).leftJoin(agentActions, eq(agentGrowthMissions.sourceActionId, agentActions.id)).where(eq(agentGrowthMissions.workspaceId, workspace.id)).orderBy(desc(agentGrowthMissions.createdAt)).limit(200);
  const active = missions.filter(({ mission }) => mission.status === 'active'); const finished = missions.filter(({ mission }) => mission.status !== 'active');
  const canUpdate = ['owner', 'admin', 'member'].includes(workspace.role);
  return <div className="app-page">
    <header className="app-page-head"><div><span>AGENT GROWTH MISSIONS</span><h1>Make the next move measurable.</h1><p>Turn evidence-linked Agent recommendations into an approved target, frozen baseline, owner, and deadline. New product evidence updates progress automatically.</p></div><div className="action-head-controls"><a className="app-primary" href="/dashboard/actions">Choose an Agent action</a><MissionRefresh enabled={canUpdate} /></div></header>
    <section className="mission-summary"><article><span>ACTIVE</span><strong>{active.length}</strong><small>missions collecting evidence</small></article><article><span>ACHIEVED</span><strong>{finished.filter(({ mission }) => mission.status === 'achieved').length}</strong><small>targets reached</small></article><article><span>NEEDS REVIEW</span><strong>{finished.filter(({ mission }) => ['missed', 'insufficient'].includes(mission.status)).length}</strong><small>missed or insufficient</small></article></section>
    <section className="mission-list"><div className="panel-title"><div><span>IN FLIGHT</span><h2>Active growth missions</h2></div><span className="status-pill">{active.length} active</span></div>{active.map(({ mission, productName, actionTitle }) => <article className="mission-card" key={mission.id} data-assessment={mission.assessment}><header><div><span>{mission.assessment.replaceAll('_', ' ').toUpperCase()} · {productName || 'REMOVED PRODUCT'}</span><h2>{mission.title}</h2></div><b>{Math.round(mission.progressPercent)}%</b></header><p>{mission.hypothesis}</p><div className="mission-track"><i style={{ width: `${Math.max(0, Math.min(100, mission.progressPercent))}%` }} /></div><div className="mission-values"><span><small>Baseline · {mission.baselineDate}</small><strong>{formatValue(mission.baselineValue, mission.currency)}</strong></span><span><small>Latest · {mission.latestDate || 'waiting'}</small><strong>{formatValue(mission.latestValue, mission.currency)}</strong></span><span><small>Target · due {mission.dueAt.slice(0, 10)}</small><strong>{formatValue(mission.targetValue, mission.currency)}</strong></span></div><footer><small>{mission.metric} · {mission.source} · {mission.limitation}</small><div>{mission.sourceAnalysisRunId && <a className="analysis-audit-link" href={`/dashboard/agent/runs/${mission.sourceAnalysisRunId}`}>Frozen evidence →</a>}<MissionCancel id={mission.id} enabled={canUpdate} /></div></footer>{actionTitle && <aside>Originating action: {actionTitle}</aside>}</article>)}{!active.length && <div className="panel-empty"><p>Open Agent actions and launch a mission from a measurable product-level recommendation.</p><a href="/dashboard/actions">Open Agent actions</a></div>}</section>
    <section className="app-panel mission-history"><div className="panel-title"><div><span>LEARNING LEDGER</span><h2>Finished missions</h2></div><span className="status-pill">{finished.length} recorded</span></div>{finished.map(({ mission, productName }) => <article className="report-row" key={mission.id}><div><strong>{mission.title}</strong><small>{productName || 'Removed product'} · {mission.metric} · {Math.round(mission.progressPercent)}% of target · {mission.finishedAt?.slice(0, 10) || 'closed'}</small></div><span>{formatValue(mission.latestValue, mission.currency)} / {formatValue(mission.targetValue, mission.currency)}</span><b data-status={mission.status}>{mission.status}</b></article>)}{!finished.length && <div className="panel-empty"><p>Completed, missed, insufficient, and cancelled missions remain here as an auditable learning history.</p></div>}</section>
  </div>;
}
