'use client';

import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import { isAgentScopeReady, type AgentScopeReadiness } from '@/lib/agent-scope';

export function ReportControls({ readinessByScope, defaultPreset, products }: { readinessByScope: AgentScopeReadiness; defaultPreset: string; products: Array<{ id: string; name: string }> }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [message, setMessage] = useState(''); const [preset, setPreset] = useState(defaultPreset); const [productId, setProductId] = useState(''); const readiness = readinessByScope[productId || 'workspace'] || {}; const ready = isAgentScopeReady(readinessByScope, productId, preset);
  async function generate(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setMessage('Running the selected Agent and composing a cited report…'); const form = new FormData(event.currentTarget); const body = { ...Object.fromEntries(form), productId: productId || null }; const response = await fetch('/api/reports', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); const result = await response.json() as { error?: string }; setPending(false); setMessage(result.error || 'Report generated and saved.'); if (response.ok) router.refresh(); }
  return <div className="report-controls"><form className="connector-form" onSubmit={generate}><h2>Generate an evidence-linked report</h2><div className="settings-grid"><label>Product scope<select name="productId" value={productId} onChange={(event) => setProductId(event.target.value)}><option value="">All products</option>{products.map((product) => <option value={product.id} key={product.id}>{product.name}</option>)}</select></label><label>Agent<select name="preset" value={preset} onChange={(event) => setPreset(event.target.value)}><option value="portfolio_analyst" disabled={!readiness.portfolio_analyst}>Portfolio Analyst{readiness.portfolio_analyst ? '' : ' · needs data'}</option><option value="revenue_analyst" disabled={!readiness.revenue_analyst}>Revenue Analyst{readiness.revenue_analyst ? '' : ' · needs data'}</option><option value="seo_growth_analyst" disabled={!readiness.seo_growth_analyst}>SEO Growth Analyst{readiness.seo_growth_analyst ? '' : ' · needs data'}</option><option value="operations_analyst" disabled={!readiness.operations_analyst}>Operations Analyst{readiness.operations_analyst ? '' : ' · needs data'}</option><option value="client_reporting_analyst" disabled={!readiness.client_reporting_analyst}>Client Reporting Analyst{readiness.client_reporting_analyst ? '' : ' · needs data'}</option></select></label><label>Period<select name="cadence" defaultValue="manual"><option value="manual">On demand</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label></div><footer><small>{ready ? 'The report and underlying Agent run share one frozen, server-locked evidence scope.' : 'This product scope needs matching evidence and a connected model.'}</small><button className="app-primary" disabled={!ready || pending}>{pending ? 'Working…' : 'Generate report'}</button></footer></form>
    {message && <p className="form-message" role="status">{message}</p>}</div>;
}
