'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';

type Schedule = { id: string; name: string; scopeLabel: string; kind: 'specialist' | 'executive'; executivePresetsJson: string; cadence: 'daily' | 'weekly' | 'monthly'; timezone: string; nextRunAt: string; lastRunAt: string | null; enabled: boolean; lastStatus: 'never' | 'success' | 'error'; lastErrorCode: string | null; consecutiveFailures: number; activeOccurrenceAt: string | null };
const errorLabels: Record<string, string> = { MODEL_UNAVAILABLE: 'Model unavailable', EVIDENCE_UNAVAILABLE: 'Matching evidence unavailable', AGENT_DISABLED: 'Agent disabled', DELIVERY_FAILED: 'Delivery failed', REPORT_GENERATION_FAILED: 'Report generation failed' };

export function ScheduleList({ schedules, canManage }: { schedules: Schedule[]; canManage: boolean }) {
  const router = useRouter(); const [pendingId, setPendingId] = useState<string | null>(null); const [message, setMessage] = useState('');
  async function toggle(schedule: Schedule) { setPendingId(schedule.id); setMessage(''); const response = await fetch('/api/report-schedules', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id: schedule.id, enabled: !schedule.enabled }) }); const result = await response.json() as { error?: string }; setPendingId(null); setMessage(result.error || (schedule.enabled ? 'Schedule paused.' : 'Schedule resumed.')); if (response.ok) router.refresh(); }
  async function remove(schedule: Schedule) { if (!window.confirm(`Delete “${schedule.name}”? Generated reports will be kept.`)) return; setPendingId(schedule.id); setMessage(''); const response = await fetch(`/api/report-schedules?id=${encodeURIComponent(schedule.id)}`, { method: 'DELETE' }); const result = await response.json() as { error?: string }; setPendingId(null); setMessage(result.error || 'Schedule deleted; generated reports were kept.'); if (response.ok) router.refresh(); }
  return <section className="app-panel schedule-panel"><div className="panel-title"><div><span>AUTOMATION</span><h2>{schedules.length ? `${schedules.length} report schedules` : 'No recurring schedule yet'}</h2></div></div>{schedules.map((schedule) => { let specialistCount = 1; if (schedule.kind === 'executive') try { specialistCount = JSON.parse(schedule.executivePresetsJson).length || 0; } catch { specialistCount = 0; } return <article className="report-row schedule-row" key={schedule.id}><div><strong>{schedule.name}</strong><small>{schedule.scopeLabel} · {schedule.kind === 'executive' ? `Executive Brief · ${specialistCount} specialists · ` : 'Specialist report · '}{schedule.enabled ? `${schedule.activeOccurrenceAt ? 'Retry' : 'Next'}: ${new Date(schedule.nextRunAt).toLocaleString('en-US', { timeZone: schedule.timezone })}` : 'Paused'} · {schedule.timezone}{schedule.lastRunAt ? ` · last attempt ${new Date(schedule.lastRunAt).toLocaleString()}` : ''}</small>{schedule.lastStatus === 'error' && <em>{errorLabels[schedule.lastErrorCode || ''] || 'Run failed'} · {schedule.consecutiveFailures} consecutive</em>}</div><span>{schedule.cadence}</span><b data-status={!schedule.enabled ? 'disabled' : schedule.lastStatus === 'error' ? 'attention' : 'ready'}>{!schedule.enabled ? 'paused' : schedule.lastStatus === 'never' ? 'scheduled' : schedule.lastStatus}</b><div className="schedule-actions"><button type="button" disabled={!canManage || pendingId === schedule.id} onClick={() => toggle(schedule)}>{schedule.enabled ? 'Pause' : 'Resume'}</button><button type="button" disabled={!canManage || pendingId === schedule.id} onClick={() => remove(schedule)}>Delete</button></div></article>; })}{message && <p className="form-message" role="status">{message}</p>}</section>;
}
