import { and, eq } from 'drizzle-orm';
import { NextResponse } from 'next/server';
import { z } from 'zod';
import { getDb } from '@/db';
import { connectorAccounts, productConnectorMappings, products } from '@/db/schema';
import { recordAuditEvent } from '@/lib/audit';
import { createAuth } from '@/lib/auth';
import { encryptSecret } from '@/lib/crypto';
import { validateLemonSqueezyCredentials } from '@/lib/lemon-squeezy-connector';
import { getPrimaryWorkspace } from '@/lib/workspaces';

const input = z.object({ displayName: z.string().trim().min(2).max(80), apiKey: z.string().trim().min(20).max(300), storeId: z.string().trim().regex(/^\d+$/), productId: z.string().uuid() });
export async function POST(request: Request) {
  const session = await createAuth().api.getSession({ headers: request.headers }); if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const workspace = await getPrimaryWorkspace(session.user.id); if (!workspace) return NextResponse.json({ error: 'Workspace not found' }, { status: 404 }); if (!['owner', 'admin'].includes(workspace.role)) return NextResponse.json({ error: 'Owner or admin access required' }, { status: 403 }); const parsed = input.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message || 'Invalid Lemon Squeezy connection' }, { status: 400 }); const [product] = await getDb().select({ id: products.id }).from(products).where(and(eq(products.id, parsed.data.productId), eq(products.workspaceId, workspace.id))).limit(1); if (!product) return NextResponse.json({ error: 'Product not found in this workspace' }, { status: 404 });
  let store: Awaited<ReturnType<typeof validateLemonSqueezyCredentials>>; try { store = await validateLemonSqueezyCredentials(parsed.data.apiKey, parsed.data.storeId); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : 'Lemon Squeezy validation failed' }, { status: 422 }); }
  const db = getDb(); const [existing] = await db.select().from(connectorAccounts).where(and(eq(connectorAccounts.workspaceId, workspace.id), eq(connectorAccounts.provider, 'lemonsqueezy'), eq(connectorAccounts.externalAccountId, store.storeId))).limit(1); const connectorId = existing?.id || crypto.randomUUID(); const encryptedCredentials = await encryptSecret(JSON.stringify({ apiKey: parsed.data.apiKey, storeId: store.storeId, storeCurrency: store.currency }), `connector:${workspace.id}:${connectorId}`);
  if (existing) await db.update(connectorAccounts).set({ displayName: parsed.data.displayName, encryptedCredentials, status: 'connected', lastCheckedAt: new Date().toISOString(), updatedAt: new Date().toISOString() }).where(and(eq(connectorAccounts.id, connectorId), eq(connectorAccounts.workspaceId, workspace.id))); else await db.insert(connectorAccounts).values({ id: connectorId, workspaceId: workspace.id, provider: 'lemonsqueezy', externalAccountId: store.storeId, displayName: parsed.data.displayName, encryptedCredentials, status: 'connected', lastCheckedAt: new Date().toISOString() });
  await db.delete(productConnectorMappings).where(and(eq(productConnectorMappings.workspaceId, workspace.id), eq(productConnectorMappings.connectorAccountId, connectorId), eq(productConnectorMappings.source, 'lemonsqueezy'))); await db.insert(productConnectorMappings).values({ id: crypto.randomUUID(), workspaceId: workspace.id, productId: product.id, connectorAccountId: connectorId, source: 'lemonsqueezy', resourceId: store.storeId, resourceLabel: `${store.displayName} · ${store.currency.toUpperCase()}`, configurationJson: JSON.stringify({ currency: store.currency }), enabled: true }); await recordAuditEvent({ workspaceId: workspace.id, actorUserId: session.user.id, action: 'connector.lemonsqueezy_connected', targetType: 'connector', targetId: connectorId, metadata: { productId: product.id, storeId: store.storeId, currency: store.currency } }); return NextResponse.json({ connector: { id: connectorId, displayName: parsed.data.displayName, storeId: store.storeId, currency: store.currency, status: 'connected' } }, { status: 201 });
}
