import { and, eq } from 'drizzle-orm';
import { NextResponse } from 'next/server';
import { z } from 'zod';
import { getDb } from '@/db';
import { connectorAccounts, productConnectorMappings, products } from '@/db/schema';
import { recordAuditEvent } from '@/lib/audit';
import { createAuth } from '@/lib/auth';
import { encryptSecret } from '@/lib/crypto';
import { validatePaddleCredentials } from '@/lib/paddle-connector';
import { getPrimaryWorkspace } from '@/lib/workspaces';

const input = z.object({ displayName: z.string().trim().min(2).max(80), apiKey: z.string().trim().min(20).max(500), environment: z.enum(['production', 'sandbox']).default('production'), productId: z.string().uuid() });

export async function POST(request: Request) {
  const session = await createAuth().api.getSession({ headers: request.headers }); if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const workspace = await getPrimaryWorkspace(session.user.id); if (!workspace) return NextResponse.json({ error: 'Workspace not found' }, { status: 404 }); if (!['owner', 'admin'].includes(workspace.role)) return NextResponse.json({ error: 'Owner or admin access required' }, { status: 403 }); const parsed = input.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message || 'Invalid Paddle connection' }, { status: 400 }); const [product] = await getDb().select({ id: products.id }).from(products).where(and(eq(products.id, parsed.data.productId), eq(products.workspaceId, workspace.id))).limit(1); if (!product) return NextResponse.json({ error: 'Product not found in this workspace' }, { status: 404 });
  let validation: Awaited<ReturnType<typeof validatePaddleCredentials>>; try { validation = await validatePaddleCredentials(parsed.data.apiKey, parsed.data.environment, workspace.id); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : 'Paddle validation failed' }, { status: 422 }); }
  const db = getDb(); const externalAccountId = `${validation.environment}:${validation.fingerprint}`; const [existing] = await db.select().from(connectorAccounts).where(and(eq(connectorAccounts.workspaceId, workspace.id), eq(connectorAccounts.provider, 'paddle'), eq(connectorAccounts.externalAccountId, externalAccountId))).limit(1); const connectorId = existing?.id || crypto.randomUUID(); const encryptedCredentials = await encryptSecret(JSON.stringify({ apiKey: parsed.data.apiKey, environment: validation.environment }), `connector:${workspace.id}:${connectorId}`);
  if (existing) await db.update(connectorAccounts).set({ displayName: parsed.data.displayName, encryptedCredentials, status: 'connected', lastCheckedAt: new Date().toISOString(), updatedAt: new Date().toISOString() }).where(and(eq(connectorAccounts.id, connectorId), eq(connectorAccounts.workspaceId, workspace.id))); else await db.insert(connectorAccounts).values({ id: connectorId, workspaceId: workspace.id, provider: 'paddle', externalAccountId, displayName: parsed.data.displayName, encryptedCredentials, status: 'connected', lastCheckedAt: new Date().toISOString() });
  await db.delete(productConnectorMappings).where(and(eq(productConnectorMappings.workspaceId, workspace.id), eq(productConnectorMappings.connectorAccountId, connectorId), eq(productConnectorMappings.source, 'paddle'))); await db.insert(productConnectorMappings).values({ id: crypto.randomUUID(), workspaceId: workspace.id, productId: product.id, connectorAccountId: connectorId, source: 'paddle', resourceId: 'seller', resourceLabel: `${validation.environment} · all transactions`, configurationJson: JSON.stringify({ environment: validation.environment }), enabled: true }); await recordAuditEvent({ workspaceId: workspace.id, actorUserId: session.user.id, action: 'connector.paddle_connected', targetType: 'connector', targetId: connectorId, metadata: { productId: product.id, environment: validation.environment, permissions: ['transaction.read', 'adjustment.read'] } }); return NextResponse.json({ connector: { id: connectorId, displayName: parsed.data.displayName, environment: validation.environment, transactionCount: validation.transactionCount, adjustmentCount: validation.adjustmentCount, status: 'connected' } }, { status: 201 });
}
