import { and, count, eq } from 'drizzle-orm';
import { NextResponse } from 'next/server';
import { z } from 'zod';
import { getDb } from '@/db';
import { calculatedMetricDefinitions, metricPoints } from '@/db/schema';
import { recordAuditEvent } from '@/lib/audit';
import { createAuth } from '@/lib/auth';
import { calculatedMetricInput, recalculateWorkspaceMetrics } from '@/lib/calculated-metrics';
import { getPrimaryWorkspace } from '@/lib/workspaces';

const removeInput = z.object({ id: z.string().uuid() });
async function context(request: Request) { const session = await createAuth().api.getSession({ headers: request.headers }); if (!session) return null; const workspace = await getPrimaryWorkspace(session.user.id); return workspace ? { session, workspace } : null; }
export async function GET(request: Request) { const value = await context(request); if (!value) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); return NextResponse.json({ definitions: await getDb().select().from(calculatedMetricDefinitions).where(eq(calculatedMetricDefinitions.workspaceId, value.workspace.id)).orderBy(calculatedMetricDefinitions.name) }); }
export async function POST(request: Request) { const value = await context(request); if (!value) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); if (!['owner', 'admin'].includes(value.workspace.role)) return NextResponse.json({ error: 'Owner or admin access required' }, { status: 403 }); const parsed = calculatedMetricInput.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message || 'Invalid calculated metric' }, { status: 400 }); const [total] = await getDb().select({ value: count() }).from(calculatedMetricDefinitions).where(eq(calculatedMetricDefinitions.workspaceId, value.workspace.id)); if (Number(total?.value || 0) >= 50) return NextResponse.json({ error: 'A workspace can contain up to 50 calculated metrics.' }, { status: 403 }); const id = crypto.randomUUID(); try { await getDb().insert(calculatedMetricDefinitions).values({ id, workspaceId: value.workspace.id, ...parsed.data, rightSource: parsed.data.rightSource || null, rightMetric: parsed.data.rightMetric || null, constantValue: parsed.data.constantValue ?? null, createdByUserId: value.session.user.id }); } catch { return NextResponse.json({ error: 'That output metric name already exists in this workspace.' }, { status: 409 }); } const calculated = await recalculateWorkspaceMetrics(value.workspace.id); await recordAuditEvent({ workspaceId: value.workspace.id, actorUserId: value.session.user.id, action: 'calculated_metric.created', targetType: 'calculated_metric', targetId: id, metadata: { metric: parsed.data.metric, leftSource: parsed.data.leftSource, leftMetric: parsed.data.leftMetric, operator: parsed.data.operator, rightSource: parsed.data.rightSource || null, rightMetric: parsed.data.rightMetric || null, usesConstant: parsed.data.constantValue !== undefined } }); return NextResponse.json({ id, calculated }, { status: 201 }); }
export async function PATCH(request: Request) { const value = await context(request); if (!value) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); if (!['owner', 'admin'].includes(value.workspace.role)) return NextResponse.json({ error: 'Owner or admin access required' }, { status: 403 }); return NextResponse.json({ calculated: await recalculateWorkspaceMetrics(value.workspace.id) }); }
export async function DELETE(request: Request) { const value = await context(request); if (!value) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); if (!['owner', 'admin'].includes(value.workspace.role)) return NextResponse.json({ error: 'Owner or admin access required' }, { status: 403 }); const parsed = removeInput.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: 'Invalid definition ID.' }, { status: 400 }); const [definition] = await getDb().select().from(calculatedMetricDefinitions).where(and(eq(calculatedMetricDefinitions.id, parsed.data.id), eq(calculatedMetricDefinitions.workspaceId, value.workspace.id))).limit(1); if (!definition) return NextResponse.json({ error: 'Calculated metric not found.' }, { status: 404 }); await getDb().delete(calculatedMetricDefinitions).where(and(eq(calculatedMetricDefinitions.id, definition.id), eq(calculatedMetricDefinitions.workspaceId, value.workspace.id))); await getDb().delete(metricPoints).where(and(eq(metricPoints.workspaceId, value.workspace.id), eq(metricPoints.source, 'calculated'), eq(metricPoints.metric, definition.metric))); await recordAuditEvent({ workspaceId: value.workspace.id, actorUserId: value.session.user.id, action: 'calculated_metric.deleted', targetType: 'calculated_metric', targetId: definition.id, metadata: { metric: definition.metric } }); return NextResponse.json({ deleted: true }); }
