import { and, desc, eq, gte, inArray, lte, max, notInArray, sql } from 'drizzle-orm';
import { ArrowDownRight, ArrowUpRight, Bot, Boxes, CalendarDays, Check, CircleAlert, Database } from 'lucide-react';
import { getDb } from '@/db';
import { agentActions, aiProviderAccounts, analysisRuns, connectorAccounts, dashboardViews, metricPoints, productConnectorMappings, productGoals, products, reportSchedules, syncRuns, workspaces } from '@/db/schema';
import { requireServerSession } from '@/lib/session';
import { getPrimaryWorkspace } from '@/lib/workspaces';
import { addRollupValue, finishRollup, type RollupAccumulator } from '@/lib/metric-rollup';
import { calculateProductHealth } from '@/lib/product-health';
import { buildActivationProgress, buildFirstValueGuide } from '@/lib/activation-progress';
import { evaluateProductGoals } from '@/lib/product-goals';
import Link from 'next/link';
import { getDeploymentLocale } from '@/lib/deployment-locale';
import { dashboardComparisonWindow } from '@/lib/dashboard-period';
import { dashboardTemplates, parseDashboardConfiguration } from '@/lib/dashboard-templates';
import { aggregateDashboardRows, buildDashboardMetricCards, selectDashboardMetrics, dashboardBreakdownMetrics, humanize, formatMetric } from '@/lib/dashboard-summary';

export default async function DashboardOverview() {
  const { user } = await requireServerSession();
  const workspace = await getPrimaryWorkspace(user.id);
  if (!workspace) return <div className="empty-state"><h1>Workspace setup needs attention</h1><p>Your account exists, but no workspace membership was found.</p></div>;
  const zh = getDeploymentLocale() === 'zh';

  const db = getDb();
  const [defaultDashboardView] = await db.select().from(dashboardViews).where(and(eq(dashboardViews.workspaceId, workspace.id), eq(dashboardViews.preset, 'indie_hacker'), eq(dashboardViews.isDefault, true))).limit(1);
  const metricScope = and(eq(metricPoints.workspaceId, workspace.id), defaultDashboardView?.productId ? eq(metricPoints.productId, defaultDashboardView.productId) : undefined, notInArray(metricPoints.metric, dashboardBreakdownMetrics));
  const [productRows, recentSyncs, healthPoints, healthDates, latestAnalysisRows, openActions, sourceMappings, connectedProviders, actedOnFindings, enabledSchedules, activeGoalRows, goalMetricRows, [latestMetricPoint]] = await Promise.all([
    db.select().from(products).where(and(eq(products.workspaceId, workspace.id), eq(products.status, 'active'))).orderBy(products.name),
    db.select().from(syncRuns).where(eq(syncRuns.workspaceId, workspace.id)).orderBy(desc(syncRuns.createdAt)).limit(6),
    db.select().from(metricPoints).where(and(eq(metricPoints.workspaceId, workspace.id), gte(metricPoints.metricDate, sql`date('now', '-13 days')`))).orderBy(metricPoints.metricDate).limit(5000),
    db.select({ split: sql<string>`date('now', '-6 days')` }).from(workspaces).where(eq(workspaces.id, workspace.id)).limit(1),
    db.select({ id: analysisRuns.id, findingsJson: analysisRuns.findingsJson, createdAt: analysisRuns.createdAt }).from(analysisRuns).where(and(eq(analysisRuns.workspaceId, workspace.id), eq(analysisRuns.status, 'success'))).orderBy(desc(analysisRuns.createdAt)).limit(1),
    db.select().from(agentActions).where(and(eq(agentActions.workspaceId, workspace.id), inArray(agentActions.status, ['suggested', 'planned', 'in_progress']))).orderBy(sql`case ${agentActions.severity} when 'critical' then 1 when 'warning' then 2 when 'opportunity' then 3 else 4 end`, desc(agentActions.lastSeenAt)).limit(3),
    db.select({ id: productConnectorMappings.id }).from(productConnectorMappings).innerJoin(connectorAccounts, eq(productConnectorMappings.connectorAccountId, connectorAccounts.id)).where(and(eq(productConnectorMappings.workspaceId, workspace.id), eq(productConnectorMappings.enabled, true), eq(connectorAccounts.status, 'connected'))).limit(1),
    db.select({ id: aiProviderAccounts.id }).from(aiProviderAccounts).where(and(eq(aiProviderAccounts.workspaceId, workspace.id), eq(aiProviderAccounts.status, 'connected'))).limit(1),
    db.select({ id: agentActions.id }).from(agentActions).where(and(eq(agentActions.workspaceId, workspace.id), inArray(agentActions.status, ['planned', 'in_progress', 'done']))).limit(1),
    db.select({ id: reportSchedules.id }).from(reportSchedules).where(and(eq(reportSchedules.workspaceId, workspace.id), eq(reportSchedules.enabled, true))).limit(1),
    db.select({ goal: productGoals, productName: products.name }).from(productGoals).innerJoin(products, eq(productGoals.productId, products.id)).where(and(eq(productGoals.workspaceId, workspace.id), eq(productGoals.enabled, true))).orderBy(productGoals.name),
    db.select({ productId: metricPoints.productId, source: metricPoints.source, metric: metricPoints.metric, metricDate: metricPoints.metricDate, value: metricPoints.value, dimensionsJson: metricPoints.dimensionsJson }).from(metricPoints).where(and(eq(metricPoints.workspaceId, workspace.id), gte(metricPoints.metricDate, sql`date('now', '-89 days')`))).limit(20000),
    db.select({ metricDate: max(metricPoints.metricDate) }).from(metricPoints).where(metricScope),
  ]);
  const overviewDates = dashboardComparisonWindow(latestMetricPoint?.metricDate, 30);
  const currentMetricRows = overviewDates ? await db.selectDistinct({ metric: metricPoints.metric }).from(metricPoints).where(and(metricScope, gte(metricPoints.metricDate, overviewDates.split), lte(metricPoints.metricDate, overviewDates.end))) : [];
  const configuredMetrics = defaultDashboardView ? parseDashboardConfiguration(defaultDashboardView.configurationJson).metrics : undefined;
  const overviewMetrics = selectDashboardMetrics(currentMetricRows.map((row) => row.metric), configuredMetrics || dashboardTemplates.indie_hacker.metrics);
  const overviewPoints = overviewDates && overviewMetrics.length ? await db.select().from(metricPoints).where(and(metricScope, inArray(metricPoints.metric, overviewMetrics), gte(metricPoints.metricDate, overviewDates.start), lte(metricPoints.metricDate, overviewDates.end))).orderBy(desc(metricPoints.metricDate)).limit(30000) : [];
  const overviewCards = buildDashboardMetricCards(overviewMetrics, aggregateDashboardRows(overviewPoints, overviewDates?.split || ''));
  const currentPointCount = overviewPoints.filter((point) => point.metricDate >= (overviewDates?.split || '')).length;
  const empty = productRows.length === 0;
  const split = healthDates[0]?.split || '9999-12-31'; const emptyRollup = (): RollupAccumulator => ({ sum: 0, count: 0, latestDate: '', latestValue: 0 });
  const healthAggregates = new Map<string, { productId: string; source: string; metric: string; current: RollupAccumulator; previous: RollupAccumulator; freshness: string }>();
  for (const point of healthPoints) { const key = `${point.productId}:${point.source}:${point.metric}`; const item = healthAggregates.get(key) || { productId: point.productId, source: point.source, metric: point.metric, current: emptyRollup(), previous: emptyRollup(), freshness: point.metricDate }; addRollupValue(point.metricDate >= split ? item.current : item.previous, point.metricDate, point.value); if (point.metricDate > item.freshness) item.freshness = point.metricDate; healthAggregates.set(key, item); }
  const productHealth = new Map(productRows.map((product) => { const values = [...healthAggregates.values()].filter((item) => item.productId === product.id); const freshness = values.map((item) => item.freshness).sort().at(-1) || null; return [product.id, calculateProductHealth({ productId: product.id, freshness, metrics: values.map((item) => ({ metric: item.metric, source: item.source, current: finishRollup(item.metric, item.current), previous: finishRollup(item.metric, item.previous) })) })]; }));
  const operatingGoals = evaluateProductGoals(activeGoalRows.map(({ goal, productName }) => ({ ...goal, productName })), goalMetricRows, new Date().toISOString().slice(0, 10)).sort((a, b) => ({ off_track: 0, at_risk: 1, no_data: 2, achieved: 3 }[a.status] - { off_track: 0, at_risk: 1, no_data: 2, achieved: 3 }[b.status]));
  let latestAnalysis: { id: string; summary: string; action: string | null; createdAt: string } | null = null; const latestRow = latestAnalysisRows[0]; if (latestRow?.findingsJson) { try { const parsed = JSON.parse(latestRow.findingsJson) as { summary?: unknown; findings?: Array<{ action?: unknown }> }; if (typeof parsed.summary === 'string') latestAnalysis = { id: latestRow.id, summary: parsed.summary, action: typeof parsed.findings?.[0]?.action === 'string' ? parsed.findings[0].action : null, createdAt: latestRow.createdAt }; } catch { /* malformed historical output stays hidden */ } }
  const activation = buildActivationProgress({ productCount: productRows.length, sourceReady: sourceMappings.length > 0, recentEvidenceCount: healthPoints.length, modelReady: connectedProviders.length > 0, successfulAnalysisCount: latestAnalysisRows.length, actedOnFindingCount: actedOnFindings.length, reportScheduleCount: enabledSchedules.length });
  const firstValue = buildFirstValueGuide({ productCount: productRows.length, sourceReady: sourceMappings.length > 0, recentEvidenceCount: healthPoints.length, modelReady: connectedProviders.length > 0, successfulAnalysisCount: latestAnalysisRows.length });

  return <div className="app-page">
    <header className="app-page-head"><div><span>{zh ? '工作空间总览' : 'WORKSPACE OVERVIEW'}</span><h1>{zh ? `你好，${user.name.split(' ')[0]}。` : `Good morning, ${user.name.split(' ')[0]}.`}</h1><p>{empty ? (zh ? '添加第一个产品，开始连接真实数据。' : 'Add your first product to begin connecting real data.') : (zh ? `正在监控工作空间中的 ${productRows.length} 个活跃产品。` : `Monitoring ${productRows.length} active product${productRows.length === 1 ? '' : 's'} across your workspace.`)}</p></div><LinkButton zh={zh} /></header>
    <section className="dashboard-status-strip overview-status-strip">
      <div><Boxes size={17} /><span>{zh ? '活跃产品' : 'Active products'}</span><strong>{productRows.length}</strong></div>
      <div><CalendarDays size={17} /><span>{zh ? '最新数据日' : 'Latest data date'}</span><strong>{overviewDates?.end || '—'}</strong></div>
      <div><Database size={17} /><span>{zh ? '本期数据点' : 'Current-period points'}</span><strong>{currentPointCount.toLocaleString(zh ? 'zh-CN' : 'en-US')}</strong></div>
    </section>
    {overviewCards.length ? <section className="dashboard-kpi-grid overview-kpi-grid">{overviewCards.map((card) => <article key={`${card.metric}:${card.currency || ''}`}><header><span>{humanize(card.metric, zh ? 'zh' : 'en')}{card.currency ? ` · ${card.currency.toUpperCase()}` : ''}</span><b>{zh ? '30 天' : '30 days'}</b></header><strong>{formatMetric(card.metric, card.current, card.currency, zh ? 'zh' : 'en')}</strong><footer><OverviewMetricChange change={card.change} zh={zh} /><small>{zh ? '对比前 30 天' : 'vs previous 30 days'}</small></footer></article>)}</section> : <section className="app-panel overview-metric-empty"><Database size={24} /><span>{zh ? '同步数据后，这里会展示数据大盘中的真实指标。' : 'Sync data to show the same real metrics used by the data dashboard.'}</span></section>}
    <p className="context-note">{zh ? `数据范围：${overviewDates?.split || '—'} 至 ${overviewDates?.end || '—'}；与数据大盘的默认视图一致。` : `Data range: ${overviewDates?.split || '—'} to ${overviewDates?.end || '—'}; matches the default data dashboard view.`} <Link href="/dashboard/views/indie_hacker?range=30">{zh ? '打开数据大盘 →' : 'Open data dashboard →'}</Link></p>
    {!firstValue.complete && <section className="first-value-guide">
      <header><div><span>{zh ? '快速开始' : 'GET STARTED'}</span><h2>{zh ? '获得第一个基于证据的答案' : 'Reach your first evidence-backed answer'}</h2><p>{zh ? '三个步骤把新工作空间变成可用的产品简报，所有进度都来自真实数据。' : 'Three steps turn a new workspace into a useful product brief.'}</p></div><b>{firstValue.completed}/{firstValue.total}</b></header>
      <div className="first-value-steps">{firstValue.steps.map((step, index) => <article key={step.id} data-state={step.state}><i>{step.complete ? <Check size={17} /> : index + 1}</i><div><span>{step.state === 'current' ? (zh ? '下一步' : 'DO THIS NEXT') : step.complete ? (zh ? '已完成' : 'COMPLETE') : (zh ? '稍后进行' : 'COMING UP')}</span><h3>{step.title}</h3><p>{step.description}</p>{step.state === 'current' && <Link className="app-primary" href={step.href}>{step.action} →</Link>}</div></article>)}</div>
    </section>}
    {firstValue.complete && <section className="activation-center" data-activated={activation.activated}>
      <header><div><span>FIRST VALUE PATH</span><h2>{activation.activated ? 'Your Agent operating loop is active.' : `${activation.completed} of ${activation.total} milestones complete`}</h2><p>{activation.next ? `Next: ${activation.next.title}. ${activation.next.description}` : 'Real evidence now flows from collection through analysis, action, and recurring delivery.'}</p></div><strong>{Math.round((activation.completed / activation.total) * 100)}%</strong></header>
      <div className="activation-progress" role="progressbar" aria-label="First value path" aria-valuemin={0} aria-valuemax={activation.total} aria-valuenow={activation.completed}><i style={{ width: `${(activation.completed / activation.total) * 100}%` }} /></div>
      <div className="activation-steps">{activation.milestones.map((milestone, index) => <Link key={milestone.id} href={milestone.href} data-state={milestone.state}><b>{milestone.complete ? <Check size={15} /> : index + 1}</b><span><strong>{milestone.title}</strong><small>{milestone.description}</small></span></Link>)}</div>
    </section>}
    <section className="agent-highlight"><div className="agent-avatar"><Bot size={24} /></div><div><span>DASHLOOM AGENT{latestAnalysis ? ` · ${latestAnalysis.createdAt.slice(0, 10)}` : ''}</span><h2>{latestAnalysis?.summary || (empty ? (zh ? 'Agent 正在等待证据。' : 'Your Agent is waiting for evidence.') : (zh ? '第一份证据简报会显示在这里。' : 'Your first evidence brief will appear here.'))}</h2><p>{latestAnalysis?.action ? `${zh ? '优先行动' : 'Priority action'}: ${latestAnalysis.action}` : empty ? (zh ? '添加产品并连接至少一个数据源；证据层为空时，Agent 不会编造分析。' : 'Add a product and connect at least one data source.') : (zh ? 'Dashloom 正在积累足够的历史数据。' : 'Dashloom is collecting enough history to cite every finding.')}</p></div><Link href={latestAnalysis ? `/dashboard/agent/runs/${latestAnalysis.id}` : '/dashboard/agent'}>{latestAnalysis ? (zh ? '检查证据 →' : 'Inspect evidence →') : (zh ? '打开 Agent →' : 'Open Agent →')}</Link></section>
    {openActions.length > 0 && <section className="app-panel overview-actions"><div className="panel-title"><div><span>AGENT ACTION CENTER</span><h2>{openActions.length} highest-priority open moves</h2></div><a href="/dashboard/actions">Manage all →</a></div>{openActions.map((action) => <article className="report-row" key={action.id}><div><strong>{action.title}</strong><small>{action.recommendedAction} · seen {action.occurrenceCount}×</small></div><span>{action.severity}</span><b data-status={action.status}>{action.status.replaceAll('_', ' ')}</b></article>)}</section>}
    {operatingGoals.length > 0 && <section className="app-panel overview-goals"><div className="panel-title"><div><span>OPERATING TARGETS</span><h2>Progress the Agent can reason about</h2></div><a href="/dashboard/products">Manage goals →</a></div>{operatingGoals.slice(0, 4).map((goal) => <article className="report-row" key={goal.goalId}><div><strong>{goal.productName} · {goal.name}</strong><small>{goal.metric} · rolling {goal.period} · {goal.currentValue === null ? 'waiting for data' : `${goal.progressPercent?.toFixed(1)}% of target`}</small></div><span>{goal.currentValue === null ? '—' : goal.currentValue.toLocaleString()} / {goal.targetValue.toLocaleString()}</span><b data-status={goal.status}>{goal.status.replaceAll('_', ' ')}</b></article>)}</section>}
    <div className="overview-columns">
      <section className="app-panel"><div className="panel-title"><div><span>PRODUCT PORTFOLIO</span><h2>Deterministic product health</h2></div><a href="/dashboard/products">Manage products →</a></div>{empty ? <EmptyProducts /> : <div className="real-product-list">{productRows.slice(0, 6).map((product) => { const health = productHealth.get(product.id); return <article key={product.id}><div>{product.name.slice(0, 1).toUpperCase()}</div><span><strong>{product.name}</strong><small>{health?.reasons[0] || product.domain || 'No metric evidence yet'}</small></span><b data-status={health?.status}>{health ? `${health.score}/100` : '—'}</b></article>; })}</div>}</section>
      <section className="app-panel"><div className="panel-title"><div><span>SYNC HEALTH</span><h2>Recent collection runs</h2></div></div>{recentSyncs.length ? <div className="sync-list-real">{recentSyncs.map((run) => <article key={run.id}><i data-status={run.status} /><span><strong>{run.source}</strong><small>{run.recordsWritten} records · {run.status}</small></span></article>)}</div> : <div className="panel-empty"><CircleAlert size={24} /><p>No synchronization has run yet.</p><a href="/dashboard/sources">Connect a source</a></div>}</section>
    </div>
  </div>;
}

function OverviewMetricChange({ change, zh }: { change: number | null; zh: boolean }) { if (change === null) return <span className="metric-change" data-tone="neutral">—</span>; const positive = change >= 0; return <span className="metric-change" data-tone={positive ? 'positive' : 'negative'}>{positive ? <ArrowUpRight size={15} /> : <ArrowDownRight size={15} />}{Math.abs(change).toFixed(1)}%{zh ? ' 较上期' : ' vs prior'}</span>; }
function LinkButton({ zh }: { zh: boolean }) { return <Link className="app-primary" href="/dashboard/sources">{zh ? '连接数据源' : 'Connect data source'}</Link>; }
function EmptyProducts() { return <div className="panel-empty"><Boxes size={28} /><p>No fictional products here. Add the first product you actually operate.</p><a href="/dashboard/products">Add a product</a></div>; }
