import { and, eq } from 'drizzle-orm';
import { NextResponse } from 'next/server';
import { z } from 'zod';
import { getDb } from '@/db';
import { connectorAccounts, productConnectorMappings, products } from '@/db/schema';
import { recordAuditEvent } from '@/lib/audit';
import { createAuth } from '@/lib/auth';
import { encryptSecret } from '@/lib/crypto';
import { validateSupabaseCredentials } from '@/lib/supabase-connector';
import { getPrimaryWorkspace } from '@/lib/workspaces';

const input = z.object({ displayName: z.string().trim().min(2).max(80), accessToken: z.string().trim().min(20).max(500), projectRef: z.string().trim().regex(/^[a-z]{20}$/), productId: z.string().uuid() });

export async function POST(request: Request) {
  const session = await createAuth().api.getSession({ headers: request.headers }); if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const workspace = await getPrimaryWorkspace(session.user.id); if (!workspace) return NextResponse.json({ error: 'Workspace not found' }, { status: 404 }); if (!['owner', 'admin'].includes(workspace.role)) return NextResponse.json({ error: 'Owner or admin access required' }, { status: 403 }); const parsed = input.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message || 'Invalid Supabase connection' }, { status: 400 }); const [product] = await getDb().select({ id: products.id }).from(products).where(and(eq(products.id, parsed.data.productId), eq(products.workspaceId, workspace.id))).limit(1); if (!product) return NextResponse.json({ error: 'Product not found in this workspace' }, { status: 404 });
  let validation: Awaited<ReturnType<typeof validateSupabaseCredentials>>; try { validation = await validateSupabaseCredentials(parsed.data.accessToken, parsed.data.projectRef); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : 'Supabase validation failed' }, { status: 422 }); }
  const db = getDb(); const externalAccountId = validation.projectRef; const [existing] = await db.select().from(connectorAccounts).where(and(eq(connectorAccounts.workspaceId, workspace.id), eq(connectorAccounts.provider, 'supabase'), eq(connectorAccounts.externalAccountId, externalAccountId))).limit(1); const connectorId = existing?.id || crypto.randomUUID(); const encryptedCredentials = await encryptSecret(JSON.stringify({ accessToken: parsed.data.accessToken, projectRef: validation.projectRef }), `connector:${workspace.id}:${connectorId}`);
  if (existing) await db.update(connectorAccounts).set({ displayName: parsed.data.displayName, encryptedCredentials, status: 'connected', lastCheckedAt: new Date().toISOString(), updatedAt: new Date().toISOString() }).where(and(eq(connectorAccounts.id, connectorId), eq(connectorAccounts.workspaceId, workspace.id))); else await db.insert(connectorAccounts).values({ id: connectorId, workspaceId: workspace.id, provider: 'supabase', externalAccountId, displayName: parsed.data.displayName, encryptedCredentials, status: 'connected', lastCheckedAt: new Date().toISOString() });
  await db.delete(productConnectorMappings).where(and(eq(productConnectorMappings.workspaceId, workspace.id), eq(productConnectorMappings.connectorAccountId, connectorId), eq(productConnectorMappings.source, 'supabase'))); await db.insert(productConnectorMappings).values({ id: crypto.randomUUID(), workspaceId: workspace.id, productId: product.id, connectorAccountId: connectorId, source: 'supabase', resourceId: validation.projectRef, resourceLabel: `${validation.projectName}${validation.region ? ` · ${validation.region}` : ''}`, configurationJson: JSON.stringify({ projectRef: validation.projectRef, region: validation.region }), enabled: true }); await recordAuditEvent({ workspaceId: workspace.id, actorUserId: session.user.id, action: 'connector.supabase_connected', targetType: 'connector', targetId: connectorId, metadata: { productId: product.id, projectRef: validation.projectRef, region: validation.region } }); return NextResponse.json({ connector: { id: connectorId, displayName: parsed.data.displayName, projectRef: validation.projectRef, projectName: validation.projectName, status: validation.status, usagePoints: validation.usagePoints } }, { status: 201 });
}
