import { and, eq, inArray, isNull, sql } from 'drizzle-orm';
import { NextResponse } from 'next/server';
import { getDb } from '@/db';
import { ingestionApiKeys, metricPoints, products } from '@/db/schema';
import { hashToken } from '@/lib/tokens';
import { ingestionPayloadSchema } from '@/lib/ingestion-contract';
import { ingestionScopeAllowsProducts } from '@/lib/ingestion-scope';

export async function POST(request: Request) { const authorization = request.headers.get('authorization') || ''; if (!authorization.startsWith('Bearer dlm_live_')) return NextResponse.json({ error: 'A Dashloom ingestion Bearer token is required' }, { status: 401 }); const token = authorization.slice(7); const [apiKey] = await getDb().select().from(ingestionApiKeys).where(and(eq(ingestionApiKeys.tokenHash, await hashToken(token)), isNull(ingestionApiKeys.revokedAt))).limit(1); if (!apiKey) return NextResponse.json({ error: 'Invalid or revoked ingestion token' }, { status: 401 }); const parsed = ingestionPayloadSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message || 'Invalid metric payload' }, { status: 400 }); const ids = [...new Set(parsed.data.rows.map((row) => row.productId))]; if (!ingestionScopeAllowsProducts(apiKey.productId, ids)) return NextResponse.json({ error: 'This ingestion token is restricted to another product.' }, { status: 403 }); const owned = await getDb().select({ id: products.id }).from(products).where(and(eq(products.workspaceId, apiKey.workspaceId), inArray(products.id, ids))); if (owned.length !== ids.length) return NextResponse.json({ error: 'A product does not belong to the token workspace' }, { status: 403 }); let written = 0; for (let index = 0; index < parsed.data.rows.length; index += 8) { const rows = parsed.data.rows.slice(index, index + 8).map((row) => ({ workspaceId: apiKey.workspaceId, productId: row.productId, source: row.source, metric: row.metric, metricDate: row.metricDate, value: row.value, dimensionsJson: JSON.stringify(row.dimensions), collectedAt: new Date().toISOString() })); await getDb().insert(metricPoints).values(rows).onConflictDoUpdate({ target: [metricPoints.workspaceId, metricPoints.productId, metricPoints.source, metricPoints.metric, metricPoints.metricDate, metricPoints.dimensionsJson], set: { value: sql`excluded.value`, collectedAt: sql`excluded.collected_at` } }); written += rows.length; } await getDb().update(ingestionApiKeys).set({ lastUsedAt: new Date().toISOString() }).where(eq(ingestionApiKeys.id, apiKey.id)); return NextResponse.json({ written, workspaceId: apiKey.workspaceId, productScope: apiKey.productId }); }
